### PR TITLE
Adding mein abfallkalender

### PR DESCRIPTION
**Pull request by deese**
I've added support for mein-abfallkalender.de source. 
This providers provides iCal for different cities. I've tested it with bad-vilbel and hofheim.

Thanks!

### CODE REVIEW

**Comment by mampfes** [comment]
Hi, I really appreciate all the effort you spent in the integration of mein-abfallkalender. I have seen that they also provide a webcal link (which could be used with the ics source or with a dedicated source). So I was wondering if it wouldn't be the better choic to let the users generate a webcal link and use this as an argument for the source instead of using the wizard or the hardcore variant. From my experience, even the wizard is too complex for many users.

**Comment by mampfes** [comment]
I tried the webcal link with the ICS source and it works perfect. There are 2 important things to mention:

1. Don't forget to add your email address, otherwise the generated webcal links don't work.
2. Replace webcal:// with https:// when the adding to the configuration.

For me, this approach looks much simpler than using a wizard of extracting 5(?) argument from the webcal URL.

**Comment by t-pohl** [comment]
Just wondering because this is exactly what I need: How do I integrate now a city which uses "mein abfallkalender"? Couldn't figure that out so far as I also cannot find it in the [Supported Service Providers](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/README.md#supported-service-providers).

**Comment by mampfes** [comment]
@t-pohl mein-abfallkalender.de is supported via the generic ICS source - see description above.

Example configurations for ICS are not listed in the Supported Service Providers list so far. I already have this in mind, but didn't find a good solution so far.

**Comment by t-pohl** [comment]
Got it to work using [this steps here](https://github.com/mampfes/hacs_waste_collection_schedule/issues/727). Would be cool to make this more prominent in the README. Otherwise really great update, thank you very much!

**Pull request closed without merging**
