### PR TITLE
Add edpevent and merge SSAM and Uppsalavatten

### PR DESCRIPTION
**Pull request by morotsgurka**
This follows a discussion on pull request #2261

I have implemented a first version of what we discussed. This creates a single source that can be used with most if not all edpevent providers. 

Functionality from both SSAM and Uppsala vatten have been merged into this to handle edge cases like returning week numbers instead of dates. 
This change would involve a **_Breaking Change_** to the users of SSAM and Uppsala Vatten. Since these would be removed. They would need to re-configure the integration using the edpevent source and then choose SSAM/Uppsala vatten and their address. Then everything should work like before.

Since the Test Cases now include tests for all the providers its a bit long. But here is the output proving that all providers seem to work and that both url or service provider can be configured:
```
Testing source edpevent_se ...
  found 3 entries for Boden - Bodens Kommun
    2024-07-29 : Deponi, Kärl 140.0l [mdi:recycle]
    2024-07-17 : Matavfall, Kärl 140.0l [mdi:food-apple]
    2024-07-17 : Brännbart, Kärl 660.0l [mdi:trash-can]
  found 7 entries for Boden - Gymnasiet
    2024-07-16 : Brännbart, Container 0m³ [mdi:trash-can]
    2024-07-16 : Matavfall, Kärl 140.0l [mdi:food-apple]
    2024-07-16 : Brännbart, Kärl 180.0l [mdi:trash-can]
    2024-07-29 : Deponi, Kärl 180.0l [mdi:recycle]
    2024-07-16 : Brännbart, Kärl 240.0l [mdi:trash-can]
    2024-07-29 : Deponi, Kärl 240.0l [mdi:recycle]
    2024-07-16 : Brännbart, Kärl 660.0l [mdi:trash-can]
  found 2 entries for Uppsalavatten - Test1
    2024-07-24 : Restavfall, Kärl 190.0l [mdi:trash-can]
    2024-07-24 : Matavfall, Kärl 130.0l [mdi:food-apple]
  found 2 entries for Uppsalavatten - Test2
    2024-07-19 : Restavfall, Kärl 660.0l [mdi:trash-can]
    2024-10-01 : Slam, Slamavskiljare 3.0m³ []
  found 3 entries for Uppsalavatten - Test3
    2024-07-19 : Restavfall, Kärl 370.0l [mdi:trash-can]
    2024-07-19 : Matavfall, Kärl 130.0l [mdi:food-apple]
    2024-08-01 : Slam, Slamavskiljare 3.0m³ []
  found 2 entries for SSAM - Home
    2024-07-25 : Kärl 1, Kärl 370.0l [mdi:help]
    2024-08-08 : Kärl 2, Kärl 370.0l [mdi:help]
  found 3 entries for SSAM - Slambrunn
    2024-07-26 : Kärl 1, Kärl 370.0l [mdi:help]
    2024-07-26 : Kärl 2, Kärl 370.0l [mdi:help]
    2025-02-01 : Slam, Slambrunn 3.0KBM []
  found 2 entries for Skelleftea - Test1
    2024-07-18 : Restavfall, Kärl 660.0L [mdi:trash-can]
    2024-07-25 : Matavfall tätt, Kärl 140.0L [mdi:food]
```

### CODE REVIEW

**Comment by 5ila5** [comment]
I like this approach. I would keep the old sources to not immediately break configurations, but just send deprecation warning and inherit from the edpevent_se source like this:

```python
import logging
from .edpevent_se import Source as EdpEventSource # type: ignore[attr-defined]

TEST_CASES = {
    "Home": {"street_address": "Asteroidvägen 1, Växjö"},
    "Bostadsrätt": {"street_address": "Långa Gatan 29 -81, Växjö"},
    "Slambrunn": {"street_address": "Svanebro Ormesberga, Ör"},
}
TITLE = "SSAM (Deprecated)"
DESCRIPTION = "Deprecated please use edpevent_se instead."
URL = "https://ssam.se"
_LOGGER = logging.getLogger(__name__)

class Source(EdpEventSource):
    def __init__(self, street_address):
        super().__init__(street_address, service_provider="ssam")
        _LOGGER.warning("ssam_se source is deprecated. Please use edpevent_se instead.")   
```

**Comment by morotsgurka** [comment]
I reverted my initial commit. Then made multiple individual commits with each change. And finally deprecated the SSAM and Uppsala Vatten sources instead of removing them. I wanted to do this before but did not know how to do it, so thanks!

Output from regular SSAM_SE:

```
Testing source ssam_se ...
The SSAM source is deprecated, please use edpevent_se instead.
  found 2 entries for Home
    2024-07-25 : Kärl 1, Kärl 370.0l [mdi:help]
    2024-08-08 : Kärl 2, Kärl 370.0l [mdi:help]
The SSAM source is deprecated, please use edpevent_se instead.
  Bostadsrätt failed: No returned building address for: Långa Gatan 29 -81, Växjö
The SSAM source is deprecated, please use edpevent_se instead.
  found 3 entries for Slambrunn
    2024-07-26 : Kärl 1, Kärl 370.0l [mdi:help]
    2024-07-26 : Kärl 2, Kärl 370.0l [mdi:help]
    2025-02-01 : Slam, Slambrunn 3.0KBM []
```
The fail on Långa Gatan 29 is i think that that address is wrong or does not have waste pickup anymore. You cant search for it on SSAMs own site.

Output from Uppsala Vatten:
```
Testing source uppsalavatten_se ...
The Uppsala Vatten och Avfall AB source is deprecated, please use edpevent_se instead
  found 2 entries for Test1
    2024-07-24 : Restavfall, Kärl 190.0l [mdi:trash-can]
    2024-07-24 : Matavfall, Kärl 130.0l [mdi:food-apple]
The Uppsala Vatten och Avfall AB source is deprecated, please use edpevent_se instead
  found 2 entries for Test2
    2024-07-19 : Restavfall, Kärl 660.0l [mdi:trash-can]
    2024-10-01 : Slam, Slamavskiljare 3.0m³ []
The Uppsala Vatten och Avfall AB source is deprecated, please use edpevent_se instead
  found 3 entries for Test3
    2024-07-19 : Restavfall, Kärl 370.0l [mdi:trash-can]
    2024-07-19 : Matavfall, Kärl 130.0l [mdi:food-apple]
    2024-08-01 : Slam, Slamavskiljare 3.0m³ []
```

And finally output from edpevent:
```
Testing source edpevent_se ...
  found 3 entries for Boden - Bodens Kommun
    2024-07-29 : Deponi, Kärl 140.0l [mdi:recycle]
    2024-07-17 : Matavfall, Kärl 140.0l [mdi:food-apple]
    2024-07-17 : Brännbart, Kärl 660.0l [mdi:trash-can]
  found 8 entries for Boden - Gymnasiet
    2024-07-23 : Brännbart, Container 0m³ [mdi:trash-can]
    2024-07-19 : Matavfall, Kärl 140.0l [mdi:food-apple]
    2024-07-23 : Matavfall, Kärl 140.0l [mdi:food-apple]
    2024-07-23 : Brännbart, Kärl 180.0l [mdi:trash-can]
    2024-07-29 : Deponi, Kärl 180.0l [mdi:recycle]
    2024-07-23 : Brännbart, Kärl 240.0l [mdi:trash-can]
    2024-07-29 : Deponi, Kärl 240.0l [mdi:recycle]
    2024-07-23 : Brännbart, Kärl 660.0l [mdi:trash-can]
  found 2 entries for Uppsalavatten - Test1
    2024-07-24 : Restavfall, Kärl 190.0l [mdi:trash-can]
    2024-07-24 : Matavfall, Kärl 130.0l [mdi:food-apple]
  found 2 entries for Uppsalavatten - Test2
    2024-07-19 : Restavfall, Kärl 660.0l [mdi:trash-can]
    2024-10-01 : Slam, Slamavskiljare 3.0m³ []
  found 3 entries for Uppsalavatten - Test3
    2024-07-19 : Restavfall, Kärl 370.0l [mdi:trash-can]
    2024-07-19 : Matavfall, Kärl 130.0l [mdi:food-apple]
    2024-08-01 : Slam, Slamavskiljare 3.0m³ []
  found 2 entries for SSAM - Home
    2024-07-25 : Kärl 1, Kärl 370.0l [mdi:help]
    2024-08-08 : Kärl 2, Kärl 370.0l [mdi:help]
  found 3 entries for SSAM - Slambrunn
    2024-07-26 : Kärl 1, Kärl 370.0l [mdi:help]
    2024-07-26 : Kärl 2, Kärl 370.0l [mdi:help]
    2025-02-01 : Slam, Slambrunn 3.0KBM []
  found 2 entries for Skelleftea - Test1
    2024-07-18 : Restavfall, Kärl 660.0L [mdi:trash-can]
    2024-07-25 : Matavfall tätt, Kärl 140.0L [mdi:food]
```

**Comment by 5ila5** [comment]
Thanks for your contribution.
I did some reformatting (based on .pre-commit-config.yaml) and added the deprecation notices in the md files of ssam and upsalla.

**Comment by morotsgurka** [comment]
Nice! Thank you and happy to help!

When do you make new releases? Perhaps a 2.0.1 update. I tried the integration by pulling the main branch in HACS and seems to work. Only thing i noticed was that there is no information on the service provider or url properties, and no hint that you only need to enter one. Other than that it seems to work!

**Comment by 5ila5** [comment]
I generally release a new version ~once a month. Maybe faster this time, as a lot of people seem to struggle with the GUI configuration finding the ICS source.

Adding additional text to some of the GUI configuration fields is not that straight forward as adding descriptions to one field adds this description to all arguments with the same name (including other sources) so we may want to either link the documentation md there or modify the implementation to somehow add individual descriptions there

**Pull request merged**
