### PR TITLE
Improve ReCollect docs

### PR DESCRIPTION
**Pull request by kaechele**

### CODE REVIEW

**Comment by mampfes** [comment]
Thanks for your contribution.

**Comment by 5ila5** [comment]
This Change will be overwritten by the `update_docu_links.py` script you need to change it in [/doc/ics/yaml/recollect.yaml ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/yaml/recollect.yaml) and run the  `update_docu_links.py` script this will automatically update the two md files

**Comment by mampfes** [comment]
Oh damn, you are right - I missed that. @kaechele: Could you fix this? Otherwise I will fix it asap.

**Comment by 5ila5** [comment]
Done in #1031

**Comment by kaechele** [comment]
Thanks :)

**Pull request merged**
