### PR TITLE
Fix Windsor and Maidenhead source

### LINKED ISSUE #2841: [Bug]: Windsor and Maidenhead - UK not working
### I Have A Problem With:

A specific source

### What's Your Problem

image

### Source (if relevant)

my.rbwm.gov.uk

### Logs

```Shell
2024-10-13 17:57:17.536 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args (PosixPath('/config/custom_components/waste_collection_schedule/sources.json'),) inside the event loop by custom integration 'waste_collection_schedule' at custom_components/waste_collection_schedule/config_flow.py, line 329: with p.open(encoding="utf-8") as json_file: (offender: /config/custom_components/waste_collection_schedule/config_flow.py, line 329: with p.open(encoding="utf-8") as json_file:), please report it to the author of the 'waste_collection_schedule' custom integration
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
self._run_once()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
handle._run()
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
return await handler(request)
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
response = await handler(request)
File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
result = await handler(request, **request.match_info)
File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
return await func(self, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
return await method(view, request, data, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 172, in post
return await self._post_impl(request, data)
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 179, in _post_impl
return await super()._post_impl(request, data)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 84, in _post_impl
result = await self._flow_mgr.async_init(
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1287, in async_init
flow, result = await self._async_init(flow_id, handler, context, data)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1312, in _async_init
flow = await self.async_create_flow(handler, context=context, data=data)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1505, in async_create_flow
flow = handler()
File "/config/custom_components/waste_collection_schedule/config_flow.py", line 304, in __init__
self._sources = self._get_source_list()
File "/config/custom_components/waste_collection_schedule/config_flow.py", line 329, in _get_source_list
with p.open(encoding="utf-8") as json_file:
```

### Relevant Configuration

_No response_

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

### PR DESCRIPTION
**Pull request by marcjay**
Council website appears to have changed, now can go directly to property with UPRN in the URL and postcode no longer required

Fixes #2841

Issue was reproducible:
```
$ ./test_sources.py -s rbwm_gov_uk -l -i
Testing source rbwm_gov_uk ...
  Windsor 1 failed: 'NoneType' object has no attribute 'startswith'
  Windsor 2 failed: 'NoneType' object has no attribute 'startswith'
  Maidenhead 1 failed: 'NoneType' object has no attribute 'startswith'
  Maidenhead 2 failed: 'NoneType' object has no attribute 'startswith'
```

With changes:
```
$ ./test_sources.py -s rbwm_gov_uk -l -i
Testing source rbwm_gov_uk ...
  found 10 entries for Windsor 1
    2024-10-15 : Garden Waste [mdi:leaf]
    2024-10-15 : Recycling [mdi:recycle]
    2024-10-22 : Recycling [mdi:recycle]
    2024-10-22 : Refuse [mdi:trash-can]
    2024-10-29 : Garden Waste [mdi:leaf]
    2024-10-29 : Recycling [mdi:recycle]
    2024-11-05 : Recycling [mdi:recycle]
    2024-11-05 : Refuse [mdi:trash-can]
    2024-11-12 : Garden Waste [mdi:leaf]
    2024-11-12 : Recycling [mdi:recycle]
  found 10 entries for Windsor 2
    2024-10-15 : Garden Waste [mdi:leaf]
    2024-10-15 : Recycling [mdi:recycle]
    2024-10-22 : Recycling [mdi:recycle]
    2024-10-22 : Refuse [mdi:trash-can]
    2024-10-29 : Garden Waste [mdi:leaf]
    2024-10-29 : Recycling [mdi:recycle]
    2024-11-05 : Recycling [mdi:recycle]
    2024-11-05 : Refuse [mdi:trash-can]
    2024-11-12 : Garden Waste [mdi:leaf]
    2024-11-12 : Recycling [mdi:recycle]
  found 10 entries for Maidenhead 1
    2024-10-15 : Recycling [mdi:recycle]
    2024-10-15 : Refuse [mdi:trash-can]
    2024-10-22 : Garden Waste [mdi:leaf]
    2024-10-22 : Recycling [mdi:recycle]
    2024-10-29 : Recycling [mdi:recycle]
    2024-10-29 : Refuse [mdi:trash-can]
    2024-11-05 : Garden Waste [mdi:leaf]
    2024-11-05 : Recycling [mdi:recycle]
    2024-11-12 : Recycling [mdi:recycle]
    2024-11-12 : Refuse [mdi:trash-can]
  found 10 entries for Maidenhead 2
    2024-10-17 : Garden Waste [mdi:leaf]
    2024-10-17 : Recycling [mdi:recycle]
    2024-10-24 : Recycling [mdi:recycle]
    2024-10-24 : Refuse [mdi:trash-can]
    2024-10-31 : Garden Waste [mdi:leaf]
    2024-10-31 : Recycling [mdi:recycle]
    2024-11-07 : Recycling [mdi:recycle]
    2024-11-07 : Refuse [mdi:trash-can]
    2024-11-14 : Garden Waste [mdi:leaf]
    2024-11-14 : Recycling [mdi:recycle]
```

### CODE REVIEW

**Comment by marcjay** [comment]
I'm afraid I don't know if removing the postcode parameter creates a breaking change for those who have this source configured already. Will re-add it if it is, but it's unused now.

**Comment by 5ila5** [comment]
This will break existing configurations, for GUI configured sources it's pretty easy to write a migration: https://github.com/mampfes/hacs_waste_collection_schedule/blob/83541a5c86729304b76c2412a6f8d8c6e20c24d6/custom_components/waste_collection_schedule/init_ui.py#L98-L155

But YAML based configs will fail.

The easiest way to resolve this is to keep the postcode parameter but with a default value and just do nothing with it and remove the postcode from the md file and add a `PARAM_TRANSLATIONS` dict to pseudo remove the postcode parameter from the GUI.

```yaml
PARAM_TRANSLATIONS = {
    "de": {
        "postcode": "(Leave Empty)",
    },
    "en": {
        "postcode": "(Leer lassen)",
    },
    "it": {
        "postcode": "(Lascia vuoto)",
    },
}
```

**Comment by marcjay** [comment]
@5ila5 thank you for the review, appreciate your time. Completely missed updating the docs the first time. Have made the changes I think you're expecting

**Comment by 5ila5** [comment]
Thanks for your contribution

**Comment by marcjay** [comment]
Thanks, realised I could have added type info back to the (now optional) arg but pushed after the merge. If you want that commit, it's at https://github.com/marcjay/hacs_waste_collection_schedule/commit/0ce6f7fef13c91d99de5a5bfffc5ccfe31fc43a8

**Comment by spattinson** [comment]
This fix works great, many thanks. The language for postcode being blank is switched between german and english.

**Comment by marcjay** [comment]
> The language for postcode being blank is switched between german and english.

Ah yes, I just copy/pasted the translations from https://github.com/mampfes/hacs_waste_collection_schedule/pull/2843#issuecomment-2410843207 without checking. I'll raise a PR to fix

**Comment by marcjay** [comment]
Raised https://github.com/mampfes/hacs_waste_collection_schedule/pull/2891 with a fix

**Pull request merged**
