### PR TITLE
Create sbazv_de.py

### PR DESCRIPTION
**Pull request by tj551955**
Hi,
I've added this file for the Südbrandenburger Abfallzweckverband (SBAZV) in Germany.
I hope this is ok. My tests were all successful.
Cheers.

### CODE REVIEW

**Comment by lal12** [comment]
I think you should your own documentation (doc/source/richmondshire_gov_uk.md) as stated in the README. Also link it in the README.md and in the info.md in the top-level directory.

**Comment by mampfes** [comment]
Please add all changes for the new source to this pull request, not one PR per file!

**Comment by tj551955** [comment]
What do you mean with that? How should I add all changes? I've added all the necessary files including all changes.

**Comment by mampfes** [comment]
You created one PR per file. Please add all files to one PR - by committing all files and then create a PR.

**Comment by tj551955** [comment]
I'm sorry, but you've lost me now. I created only one PR for one new file that I added to the sources folder (sbazv_de.py). What should I do differently?

**Comment by mampfes** [comment]
You also created 3 additional PRs for the documentation #358, #359, #360 which I closed (without merging). Please put the changes from these PRs into a single PR (this one).

**Comment by tj551955** [comment]
I have now merged all the PRs into this one as you requested. Is that ok now?

**Comment by mampfes** [comment]
Thanks for your contribution.

**Pull request merged**
