### PR TITLE
Add new attribute "abfall"

### PR DESCRIPTION
**Pull request by funknerGER**
add a new a attribute "abfall" to select specific waste types. Currently all types would be collected. If the attribute is missing, all types will be collect.

### CODE REVIEW

**Comment by funknerGER** [comment]
the new url works with this parameter "abfall=1|2|5|"

In configuration file I added this parameter:

    ...
    hausnummer: 3
    abfall: 1|2|5|
    ...

**Comment by 5ila5** [comment]
I'm generally not the biggest fan of limiting the output on source level instead of hiding them with the customize section, but it can make sense if there are a lot of potentially not needed bin types. If you want to add this option, please also add it to the documentation of that source (md file). Please also remove your commented out line completely.

**Comment by funknerGER** [comment]
I´m also not a big fan of limitation on source level, but I have in my waste collection three types of "Restmüll". This three types have identical names in the source level. So this is the only way to collect the right waste type in my case. 

> I'm generally not the biggest fan of limiting the output on source level instead of hiding them with the customize section, but it can make sense if there are a lot of potentially not needed bin types. If you want to add this option, please also add it to the documentation of that source (md file). Please also remove your commented out line completely.

**Comment by 5ila5** [comment]
Thanks for your contribution

**Pull request merged**
