### PR TITLE
Add a generic source for publidata based French areas + specific instances

### LINKED ISSUE #2547: [Source Request]: GPSEO (Grand Paris Seine & Oise)
### Municipality / Region

Yvelines North (73 Municipalities)

### Collection Calendar Webpage

https://dechets.gpseo.fr/

### Example Address

[11 Rue Jean Moulin, Mantes La Ville](https://dechets.gpseo.fr/vivre-et-habiter/gerer-mes-dechets/mes-jours-de-collecte/11-rue-jean-moulin-mantes-la-ville)

In order to get the correct written url, you should go first on : https://dechets.gpseo.fr/ 
Enter your address and you will get an URL like this : 
https://dechets.gpseo.fr/vivre-et-habiter/gerer-mes-dechets/mes-jours-de-collecte/$YOUR_VALID_ADDRESS

### Collection Data Format

As html on a webpage

### Additional Information

For each precise address it will return the specific data, no need to specify if we are : 
- Individual Clients
- Multi-family
- Companies

We can scrap data from the site result when we send a GET on the URL with the correct adress

Different Div Class for each Garbage type : 

- div  class="wrapper-block ordures-menageres"
- div  class="wrapper-block emballages"
- div  class="wrapper-block encombrants"
- div  class="wrapper-block dechets-verts"
- div  class="wrapper-block verres"

### PR DESCRIPTION
**Pull request by vinzd**
Support for schedules provided by [Publidata](https://www.publidata.io/fr/).

They operate the schedules of at least the following communities:

- GPSEO
- Orléans Métropole
- Tours métropole

A specific source is provided for GPSEO, Orléans Métropole and Tours Métropole, and the generic one is also available but requires the user to provide a parameter found by inspecting network from a browser.

The reason going for both the generic and specic approaches is to both improve discoverability of the integration for inhabitants from the three mentioned areas, and still leave the possibility to some more adventurous users from other, covered by publidata places, to benefit from it.

It’s a more generic, counter-proposal to https://github.com/mampfes/hacs_waste_collection_schedule/pull/2550 with thanks to @Crazyscorpio88, which closes #2547.

### CODE REVIEW

**Comment by 5ila5** [comment]
Thanks for your work, but I don't think extra sources that do nothing but inherit from the other source is a good idea:

For discoverability, there is the EXTRA_INFO dict (or function returning a dict) you can put in the source file it will show up in the README.md and in the HA config_flow (GUI configuration wizard) and if you select this extra info the `default_params` will be set

So this has basically all the advantages of an extra source without the drawback of additional python scripts and md files to look after.

```py
EXTRA_INFO = [
    {"title": "GPSEO Waste Collection", "url": "https://dechets.gpseo.fr/", "default_params": {"instance_id": 1292}},
    {"title": "Orléans Métropole Waste Collection", "url": "https://triermondechet.orleans-metropole.fr/", "default_params": {"instance_id": 100}},
    {"title": "Tours Métropole Waste Collection", "url": "https://www.tours-metropole.fr/", "default_params": {"instance_id": 65}},
]
```

**Comment by vinzd** [comment]
Thanks @5ila5, it’s much better with EXTRA_INFO indeed! It’s updated consequently.

**Comment by 5ila5** [comment]
Thanks for your contribution

I did some reformatting (pre-commit)

**Comment by GilDev** [comment]
Amazing! Thanks!

**Pull request merged**
