### PR TITLE
Update Oslo Kommune integration

### PR DESCRIPTION
**Pull request by dagingaa**
I updated the documentation to reflect all required fields, and added more dynamic fetching of waste collection types so that paper collection was supported too.

### CODE REVIEW

**Comment by dagingaa** [comment]
Would love eyes on this by [ccsalvesen](https://github.com/ccsalvesen) too, as he is the original author of the source.

**Comment by dagingaa** [comment]
Test output:
```
Testing source oslokommune_no ...
  found 2 entries for Villa Paradiso
    2022-10-18: Papir [mdi:newspaper-variant-multiple]
    2022-10-14: Restavfall [mdi:trash-can]
```

**Comment by mampfes** [comment]
Please add the new source to info.md and readme.md

**Comment by mampfes** [comment]
Thanks for your contribution.

**Pull request merged**
