### PR TITLE
added vancouver_ca

### PR DESCRIPTION
**Pull request by panteLx**
added vancouver_ca as requested in issue #1484

```
Testing ICS vancouver_ca
  found 31 entries for 166 W 47th Ave, Vancouver
    2023-12-06 : Green bin and recycling
    2023-12-13 : Garbage, green bin, and recycling
    2023-12-16 : Leaf collection weekend
    2023-12-17 : Leaf collection weekend
    2023-12-20 : Green bin and recycling
    2023-12-28 : Garbage, green bin, and recycling
    2024-01-05 : Green bin and recycling
    2024-01-06 : Tree chipping - various locations
    2024-01-07 : Tree chipping - various locations
    2024-01-12 : Garbage, green bin, and recycling
    2024-01-19 : Recycling
    2024-01-20 : Christmas tree & leaf collection weekend
    2024-01-21 : Christmas tree & leaf collection weekend
    2024-01-26 : Garbage, green bin, and recycling
    2024-02-02 : Recycling
    2024-02-09 : Garbage, green bin, and recycling
    2024-02-16 : Recycling
    2024-02-26 : Garbage, green bin, and recycling
    2024-03-04 : Green bin and recycling
    2024-03-11 : Garbage, green bin, and recycling
    2024-03-18 : Green bin and recycling
    2024-03-25 : Garbage, green bin, and recycling
    2024-04-03 : Green bin and recycling
    2024-04-10 : Garbage, green bin, and recycling
    2024-04-17 : Green bin and recycling
    2024-04-24 : Garbage, green bin, and recycling
    2024-05-01 : Green bin
    2024-05-08 : Garbage and green bin
    2024-05-15 : Green bin
    2024-05-23 : Garbage and green bin
    2024-05-30 : Green bin
```

### CODE REVIEW

**Comment by panteLx** [comment]
```
Testing ICS vancouver_ca
  found 31 entries for 166 W 47th Ave, Vancouver
    2023-12-06 : Green bin and recycling
    2023-12-13 : Garbage, green bin, and recycling
    2023-12-16 : Leaf collection weekend
    2023-12-17 : Leaf collection weekend
    2023-12-20 : Green bin and recycling
    2023-12-28 : Garbage, green bin, and recycling
    2024-01-05 : Green bin and recycling
    2024-01-06 : Tree chipping - various locations
    2024-01-07 : Tree chipping - various locations
    2024-01-12 : Garbage, green bin, and recycling
    2024-01-19 : Recycling
    2024-01-20 : Christmas tree & leaf collection weekend
    2024-01-21 : Christmas tree & leaf collection weekend
    2024-01-26 : Garbage, green bin, and recycling
    2024-02-02 : Recycling
    2024-02-09 : Garbage, green bin, and recycling
    2024-02-16 : Recycling
    2024-02-26 : Garbage, green bin, and recycling
    2024-03-04 : Green bin and recycling
    2024-03-11 : Garbage, green bin, and recycling
    2024-03-18 : Green bin and recycling
    2024-03-25 : Garbage, green bin, and recycling
    2024-04-03 : Green bin and recycling
    2024-04-10 : Garbage, green bin, and recycling
    2024-04-17 : Green bin and recycling
    2024-04-24 : Garbage, green bin, and recycling
    2024-05-01 : Green bin
    2024-05-08 : Garbage and green bin
    2024-05-15 : Green bin
    2024-05-23 : Garbage and green bin
    2024-05-30 : Green bin
```

**Comment by 5ila5** [comment]
vancoover.ca seems to use recollect please just add vancoover to the recollect.yaml

**Comment by panteLx** [comment]
> vancoover.ca seems to use recollect please just add vancoover to the recollect.yaml

Updated

**Comment by 5ila5** [comment]
Thanks for your contribution

**Pull request merged**
