### PR TITLE
Fix for Bristol nextCollectionDate timestamp

### PR DESCRIPTION
**Pull request by johnbutton1200**
Fix for nextCollectionDate timestamp from API containing `T01:00:00` and breaking the integration

### CODE REVIEW

**Comment by 5ila5** [comment]
Thanks four your contribution

**Comment by M21B8** [comment]
This fix doesn’t work, there’s a typo in it.

the error relates to T01:00:00

the change has T10:00:00

**Comment by johnbutton1200** [comment]
This fixed the issue for me but perhaps different hour values are returned
for different areas. Maybe a better fix would be for this to not be reliant
on specific hour values being returned to parse the date?

**Comment by M21B8** [comment]
It probably should, but I don’t get how it fixed it for you, do you not see the typo? The fix doesn’t line up with the error message.

**Comment by johnbutton1200** [comment]
Yes, sorry you are entirely correct. Please submit an updated fix if you
can. I'm away with no access to a computer for a while.

**Comment by M21B8** [comment]
https://github.com/mampfes/hacs_waste_collection_schedule/pull/1390

**Pull request merged**
