### PR TITLE
Added source for Linköping - Tekniska Verken

### PR DESCRIPTION
**Pull request by juppe1969**
This adds a source for Linköping - Tekniska Verken, serving the municipality of Linköping, Sweden.

### CODE REVIEW

**Comment by mampfes** [comment]
Thanks for your contribution.

**Comment by juppe1969** [comment]
When will my changes show up in the master branch? Cant see them there now.

**Comment by juppe1969** [comment]
Looks like your last commit deleted my changes.

**Comment by mampfes** [comment]
Oh, yes - sorry for that. You uses a strange character encoding which killed the whole docu. While repairing it I accidently remove the original file.

**Comment by juppe1969** [comment]
I'll fix it tomorrow.

**Pull request merged**
