### PR TITLE
Add support for Colchester.gov.uk for United Kingdom

### PR DESCRIPTION
**Pull request by Canis-L-Sapien**
Add support for waste removal the borough of Colchester, United Kingdom

### CODE REVIEW

**Comment by Canis-L-Sapien** [comment]
Noticed bug with future collections

**Comment by mampfes** [comment]
Hi, your service provider uses an interesting data format. Could you please add an description (either here or better directly in the source code) this magic with `WeekOne` true/false works?

**Comment by Canis-L-Sapien** [comment]
@mampfes added some explanation in comments in the code

**Comment by mampfes** [comment]
Thanks for your contribution.

**Pull request merged**
