### PR TITLE
Add HVCGroep waste management

### PR DESCRIPTION
**Pull request by Techwolf12**
This will add waste management from the Dutch HVCGroep ([hvcgroep.nl](https://www.hvcgroep.nl/).) 
In case you want to validate the results, they can be manually seen at https://www.hvcgroep.nl/zelf-regelen/afvalkalender

### CODE REVIEW

**Comment by mampfes** [comment]
Thanks for your contribution and sorry that I didn't respond earlier. Somehow I didn't get notification for this repo since 2 months.

**Comment by mampfes** [comment]
The source fails for the 1st test case:
```
Traceback (most recent call last):
  File "./test_sources.py", line 52, in main
    result = source.fetch()
  File "hacs_waste_collection_schedule/custom_components/waste_collection_schedule/waste_collection_schedule/source/hvcgroep_nl.py", line 39, in fetch
    bag_id = data[0]["bagid"]
IndexError: list index out of range
```

Could you please provide a valid test case?
And the if statement in line 41 should be moved in front of the array access in line 38. And a log output would be helpful in this case.

**Comment by Techwolf12** [comment]
No worries about the wait!

And strange, I'll check the test cases and add some error handling/logging, probably next weekend. At least it does seem to work in Hass:
afbeelding

**Comment by mampfes** [comment]
I had some spare time today: I already improved the error logging and moved the if statement to the right position. I also removed the failed test case, but I would really appreciate it if you could check this one again:
```
    "Obdam": {
        "postal_code": "1713VM",
        "house_number": "1",
    },
```

The other changes are caused by pylint.

**Pull request merged**
