### PR TITLE
Add source for Richmondshire, North Yorkshire

### PR DESCRIPTION
**Pull request by theanorak-keith**
Apologies if this is problematic, my first pull request.

### CODE REVIEW

**Comment by lal12** [comment]
I think you should your own documentation (doc/source/richmondshire_gov_uk.md) as stated in the README. Also link it in the README.md and in the info.md in the top-level directory.

**Comment by theanorak-keith** [comment]
> I think you should your own documentation (doc/source/richmondshire_gov_uk.md) as stated in the README. Also link it in the README.md and in the info.md in the top-level directory.

Will do.

**Comment by dt215git** [comment]
A lot of the other UK-based entries that work via the UPRN suggest using [findmyaddress.co.uk](https://www.findmyaddress.co.uk/) to identify a properties UPRN.
Your .md could also include that approach, in addition to in the method you have commented in the code.
Many ways to skin a cat, and all that..

**Comment by mampfes** [comment]
Thanks for your contribution.

**Pull request merged**
