### PR TITLE
Adding my waste mobi

### PR DESCRIPTION
**Pull request by expl0ratory**
I watched network requests on my city's lookup tool and found the same site powers many cities in the USA.

This sends requests to three separate end points spread across recyclecoach.com and my-waste.mobi (their app)

### CODE REVIEW

**Comment by 5ila5** [comment]
Is it possible to write a helper function to generate [EXTRA_INFO](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/contributing_source.md#update-links-in-readmemd-and-infomd) for all supported cities/areas to add supported areas to the `readme.md` and `info.md`
just some testing (only returns limited number returns possibly cities that do not support pickup date scheduling):

```python
def generate_extra_info():
    res = requests.get(city_finder, params={'find': ' '})
    
    EXTRA_INFO:list[dict] = []
    
    for city in res.json()["cities"]:
        country = city["country_cd"]
        
        COUNTRY_MAP = {
            "Brazil": "br",
            "Ireland": "ie",
            "(UK)": "uk",
            "USA": "us",
            "ARG": "ar",
            "HK": "hk",
            "New Zealand": "nz",
            "Canada": "ca",
        }
        
        for key, value in COUNTRY_MAP.items():
            if city["google_search_term"].endswith(key):
                country = value
                break    
            
        if country == None:
            print("Unknown country:", city["google_search_term"])
            country = ""
    
        EXTRA_INFO.append({
            "title": city["google_search_term"],
            "country":country.lower(),
        })
        
    print("EXTRA_INFO =", json.dumps(EXTRA_INFO))
 ```

Please rename your source from `my-waste_mobi[.md|.py]` to `my_waste_mobi[.md|.py]` for constant naming across sources.

Please remove or at least reduce your comments about the responses

**Comment by expl0ratory** [comment]
> Is it possible to write a helper function to generate [EXTRA_INFO](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/contributing_source.md#update-links-in-readmemd-and-infomd) for all supported cities/areas to add supported areas to the `readme.md` and `info.md` just some testing (only returns limited number returns possibly cities that do not support pickup date scheduling):

The endpoint only returns 30 records per request.  I believe looking at the stage assigned to the city in the result indicates whether or not they have calendar data (stage 3 vs 1 or 2.)  
 
I added in functionality to fail and log if using a city that doesn't have support based on that.

I'm trying to come up with a reasonable way to get a definitive list.

> Please rename your source from `my-waste_mobi[.md|.py]` to `my_waste_mobi[.md|.py]` for constant naming across sources.
> Please remove or at least reduce your comments about the responses

Sure thing

**Comment by 5ila5** [comment]
If there is no good way to get all supported areas, we should remove this function and just add known supported areas to the EXTRA_INFO parameter

**Comment by expl0ratory** [comment]
Did some scripting and manual looking to add several municipalities.  Renamed it to the company name since initial name is app/not how they talk about themselves

**Comment by 5ila5** [comment]
Thanks for your contribution.


--

Source will be part of the 1.41.0 release (or now as master (git version))

**Pull request merged**
