### PR TITLE
Add source for stonnington.vic.gov.au

### PR DESCRIPTION
**Pull request by tathamoddie**
This is a major council area in inner city Melbourne, Victoria, Australia.

### CODE REVIEW

**Comment by tathamoddie** [comment]
@mampfes Since #102 was landed first, this wasn't going to apply cleanly anymore. I've just rebased it. Hopefully good-to-go again. Thanks!

**Comment by mampfes** [comment]
Damn, I made a mistake. I will reopen the PR.

**Comment by mampfes** [comment]
Thanks for your contribution.

**Comment by tathamoddie** [comment]
Thanks for the rapid review, improvements, and merge!

**Pull request merged**
