### PR TITLE
Waste calendar for Köflach, Austria

### PR DESCRIPTION
**Pull request by wehrmannit**
Added three test cases.

Extracted the dates from a PDF, added it to a small Heroku script and voila.

Testing source koeflach_at ...
  found 23 entries for Köfach - Ackerweg
    2024-10-01 : Restmüll [mdi:trash-can]
    2024-10-29 : Restmüll [mdi:trash-can]
    2024-11-26 : Restmüll [mdi:trash-can]
    2024-12-23 : Restmüll [mdi:trash-can]
    2024-09-19 : Leichtverpackung [mdi:recycle]
    2024-10-31 : Leichtverpackung [mdi:recycle]
    2024-12-12 : Leichtverpackung [mdi:recycle]
    2024-09-20 : Bio-Tonne [mdi:leaf]
    2024-09-27 : Bio-Tonne [mdi:leaf]
    2024-10-04 : Bio-Tonne [mdi:leaf]
    2024-10-11 : Bio-Tonne [mdi:leaf]
    2024-10-18 : Bio-Tonne [mdi:leaf]
    2024-10-25 : Bio-Tonne [mdi:leaf]
    2024-11-02 : Bio-Tonne [mdi:leaf]
    2024-11-08 : Bio-Tonne [mdi:leaf]
    2024-11-22 : Bio-Tonne [mdi:leaf]
    2024-12-06 : Bio-Tonne [mdi:leaf]
    2024-12-20 : Bio-Tonne [mdi:leaf]
    2024-10-28 : Papiertonne [mdi:package-variant]
    2024-12-09 : Papiertonne [mdi:package-variant]
    2024-09-30 : Bio-Tonne Reinigung [mdi:leaf]
    2024-10-28 : Bio-Tonne Reinigung [mdi:leaf]
    2024-11-25 : Bio-Tonne Reinigung [mdi:leaf]
  found 32 entries for Köfach - Am Wald
    2024-09-25 : Restmüll [mdi:trash-can]
    2024-10-22 : Restmüll [mdi:trash-can]
    2024-11-19 : Restmüll [mdi:trash-can]
    2024-12-17 : Restmüll [mdi:trash-can]
    2024-09-18 : Leichtverpackung [mdi:recycle]
    2024-10-30 : Leichtverpackung [mdi:recycle]
    2024-12-11 : Leichtverpackung [mdi:recycle]
    2024-09-19 : Bio-Tonne [mdi:leaf]
    2024-09-26 : Bio-Tonne [mdi:leaf]
    2024-10-03 : Bio-Tonne [mdi:leaf]
    2024-10-10 : Bio-Tonne [mdi:leaf]
    2024-10-17 : Bio-Tonne [mdi:leaf]
    2024-10-24 : Bio-Tonne [mdi:leaf]
    2024-10-31 : Bio-Tonne [mdi:leaf]
    2024-11-07 : Bio-Tonne [mdi:leaf]
    2024-11-21 : Bio-Tonne [mdi:leaf]
    2024-12-05 : Bio-Tonne [mdi:leaf]
    2024-12-19 : Bio-Tonne [mdi:leaf]
    2024-09-24 : Papiertonne [mdi:package-variant]
    2024-11-05 : Papiertonne [mdi:package-variant]
    2024-12-17 : Papiertonne [mdi:package-variant]
    2024-10-08 : Restmüll Zwischenabholung [mdi:trash-can]
    2024-11-05 : Restmüll Zwischenabholung [mdi:trash-can]
    2024-12-03 : Restmüll Zwischenabholung [mdi:trash-can]
    2024-12-31 : Restmüll Zwischenabholung [mdi:trash-can]
    2024-09-29 : Bio-Tonne Reinigung [mdi:leaf]
    2024-10-27 : Bio-Tonne Reinigung [mdi:leaf]
    2024-11-24 : Bio-Tonne Reinigung [mdi:leaf]
    2024-10-09 : Papiertonne Zwischenabholung [mdi:package-variant]
    2024-10-24 : Papiertonne Zwischenabholung [mdi:package-variant]
    2024-11-20 : Papiertonne Zwischenabholung [mdi:package-variant]
    2024-12-05 : Papiertonne Zwischenabholung [mdi:package-variant]
  found 33 entries for Köfach - Lagerstraße
    2024-10-03 : Restmüll [mdi:trash-can]
    2024-10-31 : Restmüll [mdi:trash-can]
    2024-11-28 : Restmüll [mdi:trash-can]
    2024-12-27 : Restmüll [mdi:trash-can]
    2024-09-20 : Leichtverpackung [mdi:recycle]
    2024-11-02 : Leichtverpackung [mdi:recycle]
    2024-12-13 : Leichtverpackung [mdi:recycle]
    2024-09-19 : Bio-Tonne [mdi:leaf]
    2024-09-26 : Bio-Tonne [mdi:leaf]
    2024-10-03 : Bio-Tonne [mdi:leaf]
    2024-10-10 : Bio-Tonne [mdi:leaf]
    2024-10-17 : Bio-Tonne [mdi:leaf]
    2024-10-24 : Bio-Tonne [mdi:leaf]
    2024-10-31 : Bio-Tonne [mdi:leaf]
    2024-11-07 : Bio-Tonne [mdi:leaf]
    2024-11-21 : Bio-Tonne [mdi:leaf]
    2024-12-05 : Bio-Tonne [mdi:leaf]
    2024-12-19 : Bio-Tonne [mdi:leaf]
    2024-09-18 : Papiertonne [mdi:package-variant]
    2024-10-30 : Papiertonne [mdi:package-variant]
    2024-12-11 : Papiertonne [mdi:package-variant]
    2024-09-17 : Restmüll Zwischenabholung [mdi:trash-can]
    2024-10-15 : Restmüll Zwischenabholung [mdi:trash-can]
    2024-11-12 : Restmüll Zwischenabholung [mdi:trash-can]
    2024-12-10 : Restmüll Zwischenabholung [mdi:trash-can]
    2024-09-29 : Bio-Tonne Reinigung [mdi:leaf]
    2024-10-27 : Bio-Tonne Reinigung [mdi:leaf]
    2024-11-24 : Bio-Tonne Reinigung [mdi:leaf]
    2024-09-30 : Papiertonne Zwischenabholung [mdi:package-variant]
    2024-10-16 : Papiertonne Zwischenabholung [mdi:package-variant]
    2024-11-13 : Papiertonne Zwischenabholung [mdi:package-variant]
    2024-11-27 : Papiertonne Zwischenabholung [mdi:package-variant]
    2024-12-23 : Papiertonne Zwischenabholung [mdi:package-variant]

### CODE REVIEW

**Comment by 5ila5** [comment]
I would like to say somewhere that this data does not come from an unofficial website but a third party one.
Maybe `(unoffical)` in the title and some explanation in the md

You have some copy-paste remainings in your md file (Dorset Council)


I tried to integrate the [Lipizzanerheimat App](https://play.google.com/store/apps/details?id=com.jolioo.mobileapp.lipizzanerheimatapp), which would make this source redundant, but they do some weird API key hashing I could not figure out

**Comment by wehrmannit** [comment]
@5ila5 that was my first try, their API is... weird. I was able to reuse my "own" key but it never lasted. Maybe I am able to work this one out instead of my ICS converter tool

**Comment by 5ila5** [comment]
I did some digging around, they sha1 hash some mix of data, key, secret


Renamed by me so I'm not 100% sure thy are correct.

```javascript
value: function (auth_token, path, data_1, device_secret) {
        if (device_secret)
          return data_1 || auth_token
            ? data_1 && !auth_token
              ? require('./436').sha1(device_secret + '@' + path + '@' + data_1)
              : !data_1 && auth_token
              ? require('./436').sha1(device_secret + '@' + auth_token + '@' + path + '@')
              : require('./436').sha1(device_secret + '@' + auth_token + '@' + path + '@' + data_1)
            : require('./436').sha1(device_secret + '@' + path + '@');
        else
          return data_1 || auth_token
            ? data_1 && !auth_token
              ? require('./436').sha1(require('./445').APISECRET + '@' + path + '@' + data_1)
              : !data_1 && auth_token
              ? require('./436').sha1(require('./445').APISECRET + '@' + auth_token + '@' + path + '@')
              : require('./436').sha1(require('./445').APISECRET + '@' + auth_token + '@' + path + '@' + data_1)
            : require('./436').sha1(require('./445').APISECRET + '@' + path + '@');
      },
```

I couldn't figure out more details and I do not think it is realistic to get this working, We would need to hard-code the API_KEYS as well which may change in the future

**Comment by wehrmannit** [comment]
> I did some digging around, they sha1 hash some mix of data, key, secret
> 
> Renamed by me so I'm not 100% sure thy are correct.
> 
> ```js
> value: function (auth_token, path, data_1, device_secret) {
>         if (device_secret)
>           return data_1 || auth_token
>             ? data_1 && !auth_token
>               ? require('./436').sha1(device_secret + '@' + path + '@' + data_1)
>               : !data_1 && auth_token
>               ? require('./436').sha1(device_secret + '@' + auth_token + '@' + path + '@')
>               : require('./436').sha1(device_secret + '@' + auth_token + '@' + path + '@' + data_1)
>             : require('./436').sha1(device_secret + '@' + path + '@');
>         else
>           return data_1 || auth_token
>             ? data_1 && !auth_token
>               ? require('./436').sha1(require('./445').APISECRET + '@' + path + '@' + data_1)
>               : !data_1 && auth_token
>               ? require('./436').sha1(require('./445').APISECRET + '@' + auth_token + '@' + path + '@')
>               : require('./436').sha1(require('./445').APISECRET + '@' + auth_token + '@' + path + '@' + data_1)
>             : require('./436').sha1(require('./445').APISECRET + '@' + path + '@');
>       },
> ```
> 
> I couldn't figure out more details and I do not think it is realistic to get this working, We would need to hard-code the API_KEYS as well which may change in the future

Hey. I admit this issue annoyed me way too much.

In the app there is a file with "guest" credentials that I used to reverse engineer the api hash.

```javascript
var crypto = require('crypto')

const sha1 = function (input) {
    return crypto.createHash('sha1').update(input).digest('hex')
}

function apiHash(t, n, u, s) {
    return sha1(APISECRET + '@' + n + '@' + u)
}

let output = apiHash(null, "api/mobile-app/garbagecalendar", "garbage_calendar_id=xxx&language=de", undefined);

``` 

So it's rather simple. The Authorization header is just the guest user/password, the apikey the guest apikey. 

<details><summary>Details</summary>
<p>

{
    "device": null,
    "success": true,
    "error": null,
    "data": {
        "init_month": 12,
        "garbage_calendar_year": 2024,
        "labels": [
            {
                "garbage_label_id": 18325,
                "garbage_label_id_parent": null,
                "garbage_label_title": "Müll"
            },
            {
                "garbage_label_id": 18326,
                "garbage_label_id_parent": 18325,
                "garbage_label_title": "Bioabfall",
                "garbage_label_label": "B",
                "garbage_label_label_html": "<span class=\"garbage-label\" style=\"background-color: #673a15; color: #ffffff;\">B</span>",
                "garbage_label_background_color": "#673a15",
                "garbage_label_text_color": "#ffffff"
            },
            {
                "garbage_label_id": 18327,
                "garbage_label_id_parent": 18325,
                "garbage_label_title": "Kunststoffverpackung",
                "garbage_label_label": "K",
                "garbage_label_label_html": "<span class=\"garbage-label\" style=\"background-color: #ffec00; color: #ffffff;\">K</span>",
                "garbage_label_background_color": "#ffec00",
                "garbage_label_text_color": "#ffffff"
            },
            {
                "garbage_label_id": 18328,
                "garbage_label_id_parent": 18325,
                "garbage_label_title": "Restmüll",
                "garbage_label_label": "R",
                "garbage_label_label_html": "<span class=\"garbage-label\" style=\"background-color: #191919; color: #ffffff;\">R</span>",
                "garbage_label_background_color": "#191919",
                "garbage_label_text_color": "#ffffff"
            },
            {
                "garbage_label_id": 18329,
                "garbage_label_id_parent": 18325,
                "garbage_label_title": "Altpapier",
                "garbage_label_label": "A",
                "garbage_label_label_html": "<span class=\"garbage-label\" style=\"background-color: #e30613; color: #ffffff;\">A</span>",
                "garbage_label_background_color": "#e30613",
                "garbage_label_text_color": "#ffffff"
            },
            {
                "garbage_label_id": 18330,
                "garbage_label_id_parent": 18325,
                "garbage_label_title": "Gefäßreinigung Bioabfall",
                "garbage_label_label": "GB",
                "garbage_label_label_html": "<span class=\"garbage-label\" style=\"background-color: #673a15; color: #ffffff;\">GB</span>",
                "garbage_label_background_color": "#673a15",
                "garbage_label_text_color": "#ffffff"
            }
        ],
        "holidays": [],
        "items": [
            {
                "garbage_calendar_item_date": "16.12.2024",
                "garbage_label_id": 18328,
                "opening_hours": null,
                "comment": null
            },
            {
                "garbage_calendar_item_date": "19.12.2024",
                "garbage_label_id": 18326,
                "opening_hours": null,
                "comment": "Bitte kein Plastik in die Biotonne!"
            },
            {
                "garbage_calendar_item_date": "19.12.2024",
                "garbage_label_id": 18329,
                "opening_hours": null,
                "comment": null
            }
        ],
        "hotspot_infos": [],
        "garbage_calendar_notification_active": false
    }
}

</p>
</details> 


Do you reckon I should rewrite this extension to work with all Lippizianerheimat?

**Comment by 5ila5** [comment]
It would generally be nice if this would work.

Any reason you closed this and removed your commits?

**Pull request closed without merging**
