### PR TITLE
Update northlincs_gov_uk.py

### PR DESCRIPTION
**Pull request by Media-1**
Some dates in NorthLincs JSON contained "(*)", cleaned formatting and removed

### CODE REVIEW

**Comment by 5ila5** [comment]
cold you provide a test case where this is a problem.

for our test cases dates can look like this `2023-12-29 (*)` but this is not a problem because the (*) part is removed by `.split(" ")[0]`

**Comment by Media-1** [comment]
Sure, here's the error I get with a fresh plugin installation.

`fetch failed for source North Lincolnshire Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/northlincs_gov_uk.py", line 39, in fetch date = datetime.strptime(collection["CollectionDate"], "%Y-%m-%d").date() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/_strptime.py", line 568, in _strptime_datetime tt, fraction, gmtoff_fraction = _strptime(data_string, format) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/_strptime.py", line 352, in _strptime raise ValueError("unconverted data remains: %s" % ValueError: unconverted data remains: (*) `

**Comment by 5ila5** [comment]
I'm sorry this might have been not clear enough. I meant a test case for the TEST_CASES variable (an example UPRN) where this happens. This might be helpful if there is ever a problem in the future.

**Comment by Media-1** [comment]
I apologise, sure - 200000870043

**Comment by 5ila5** [comment]
Sorry did not get that earlier but this fixes something that is allready fixed by #1355

fix #1355 will be part of release 1.44.0 or is available now as master (git) version (HACS: 3-dot menu -> re-download -> change version to master)

**Pull request closed without merging**
