### PR TITLE
Docu links

### PR DESCRIPTION
**Pull request by dt215git**
Great job on the automated document update script - certainly makes things easier! :+1: 

The Service Provider section for the README is slightly off 
image

Just an extra "\n" needed in the `update_docu_links.py` and a carriage return after the `<summary>ICS/iCal and User-Specified</summary>`
image

### CODE REVIEW

**Comment by mampfes** [comment]
Ups, thank you very much. The markdown looked good in my local md renderer. And to be honest - I didn't check the result in GitHub.
There are some more multi-district sources which I want to improve so that they add more links.

**Comment by dt215git** [comment]
No problem.
Could you run this script using a GitHub Action triggered when you merged PR's? That'd reduce contributions to just the service provider .py and .md files?

**Comment by mampfes** [comment]
Interesting idea. I have no experience with Github Actions. Another possibility would be a commit hook.

**Comment by dt215git** [comment]
Just started looking at Actions and have come up with one that runs a `.py` script and commits any changes back to the repo. The `change_log.py` script it runs just appends some info to a text file, which is fine for what I needed. It's a bit simplistic in comparison to your `update_docu_links.py` script, but the overall principles are much the same. I'm sure it could be improved, but it's a first attempt and didn't take too long to come up with.
 
It's manually triggered from the Actions tab at the moment, but the process seems to work okay for what I'm wanting to do. I 
imagine it could be configured to run on some other trigger - the docs for those are a bit confusing :confused:. Having said that,  your `update_docu_links.py` script would only need to run if a source is added/removed, so maybe having it run on every commit/merge is a bit excessive.

Anyway, this is the yaml I came up with - just in case you're interested.

```yaml
# REFERENCES:
# https://github.com/actions/checkout
# https://github.com/actions/setup-python
# https://github.com/marketplace/actions/git-auto-commit

# This workflow is manually triggered from the Actions tab
name: Manual workflow (update log.txt)

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo Contents
        uses: actions/checkout@v3  # Checkout the repository content

      - name: Setup Python Environment
        uses: actions/setup-python@v4  # Set up python environment
        with:
          python-version: "3.10"  # Install python version

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip  # make sure latest pip version is used
        # run: python -m pip install --upgrade <package names>
        # run: pip install -r auto_requirements.txt  # Refers to dependencies needed for the subsequent script, not the whole project!

      - name: Execute Python script
        run: python change_log.py  # Run the script(s)

      - name: Commit changed file back to repo
        uses: stefanzweifel/git-auto-commit-action@v4 # Automatically commit the changed file(s)
        with:
          commit_message: Automated Commit (GitHub Action)
          # commit_user_name: My GitHub Actions Bot # defaults to "github-actions[bot]"
          # commit_user_email: my-github-actions-bot@example.org # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
          # commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run
```

**Pull request merged**
