### PR TITLE
Resolve broken proxy for nottingham city and simplify json processing

### PR DESCRIPTION
**Pull request by TurnrDev**
Not sure exactly when proxy broke, but it's broken.

### CODE REVIEW

**Comment by 5ila5** [comment]
Thanks for your contribution

**Comment by TurnrDev** [comment]
When can we expect the next release?

**Comment by 5ila5** [comment]
I release a new version ruffly every month, or when I think it happened enough to justify a release, but you can use the master/git version with HACS which is the current development status. As far as I noticed, it will prompt you to update to the normal releases when there is a new release


install master/git version: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA


<details><summary>Older versions of HACS:</summary>
<p>
install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
</p>
</details>

**Comment by TurnrDev** [comment]
Thank you, I never knew I could do that!

**Pull request merged**
