### PR TITLE
add St Albans, UK

### LINKED ISSUE #2311: [Feature]:  Add support for St. Albans
### I propose a feature for:

Sources

### Describe your wanted feature

Please add https://www.stalbans.gov.uk/rubbish-collections

Thanks!

### PR DESCRIPTION
**Pull request by 5ila5**
closes #2311

### CODE REVIEW

**Comment by bonstio** [comment]
That was extremely fast <3

**Comment by bonstio** [comment]
Can we get this into a release, please?

**Comment by 5ila5** [comment]
Just released 2.1.0

**Comment by bonstio** [comment]
Awesome, thanks!

**Pull request merged**
