### PR TITLE
Add source for Breckland Council, UK

### LINKED ISSUE #499: Support request for Breckland
https://www.breckland.gov.uk/mybreckland

 Post Code: IP22 2LJ

I'm running HA in VirtualBox and can't find a way to run the python script, but digging into the code this looks promising...

{"jsonrpc":"2.0","id":"1671645668056","method":"Breckland.Whitespace.JointWasteAPI.GetBinCollectionsByUprn","params":{"uprn":"100091308629","environment":"live"}}

### PR DESCRIPTION
**Pull request by bbr111**
Add source for Breckland Council, UK

resolve #499

### CODE REVIEW

**Review by danwooller — CHANGES_REQUESTED** [review]
At line 44/45, it doesn't account for a property with a number instead of a name.

Please add:

            elif self._address.lower() in key['number'].lower():
                uprn = (key['uprn'])

**Comment by bbr111** [comment]
I currently only use the name.

but i can make it to use uprn instead.

the field number is not field in my examples:

```
{
	"id": "5",
	"result": [
		{
			"number": "",
			"name": "FIR TREE COTTAGE",
			"prefix": "",
			"address1": "",
			"address2": "THE GREEN",
			"town": "DISS",
			"county": "NORFOLK",
			"postcode": "IP22 2LJ",
			"northing": "281444",
			"easting": "604231",
			"siteId": "219653",
			"uprn": "100091308629"
		},
		{
			"number": "",
			"name": "GLEN TRAVIS",
			"prefix": "",
			"address1": "",
			"address2": "THE GREEN",
			"town": "DISS",
			"county": "NORFOLK",
			"postcode": "IP22 2LJ",
			"northing": "281472",
			"easting": "604222",
			"siteId": "220460",
			"uprn": "10011972067"
		},
		{
			"number": "",
			"name": "OAKLEY HOUSE",
			"prefix": "",
			"address1": "",
			"address2": "THE GREEN",
			"town": "DISS",
			"county": "NORFOLK",
			"postcode": "IP22 2LJ",
			"northing": "281492.21",
			"easting": "604194.56",
			"siteId": "225901",
			"uprn": "10011977093"
		},
		{
			"number": "",
			"name": "PRIMROSE LODGE",
			"prefix": "",
			"address1": "",
			"address2": "THE GREEN",
			"town": "DISS",
			"county": "NORFOLK",
			"postcode": "IP22 2LJ",
			"northing": "281487.91",
			"easting": "604216.43",
			"siteId": "227450",
			"uprn": "10011977608"
		},
		{
			"number": "",
			"name": "THE COURT",
			"prefix": "",
			"address1": "",
			"address2": "THE GREEN",
			"town": "DISS",
			"county": "NORFOLK",
			"postcode": "IP22 2LJ",
			"northing": "281448",
			"easting": "604166",
			"siteId": "236038",
			"uprn": "10011965928"
		}
	],
	"jsonrpc": "2.0"
}```

**Comment by bbr111** [comment]
@danwooller 

If made some changes. 

Added support for uprn directly.

you now can use postcode and address or just provide the uprn.

Added the ICON_MAP from your code.

**Comment by danwooller** [comment]
@bbr111 Thanks for that, and thanks for working out the code, I'm looking forward to getting this integrated into HA.

**Comment by mampfes** [comment]
Thanks for your contribution.

**Pull request merged**
