### PR TITLE
Added Toronto Canada source

### PR DESCRIPTION
**Pull request by constvariable**
Adding source that pulls from toronto.ca website to get Garbage, YardWaste, GreenBin, Recycling, and ChristmasTree pickup schedule. Works for greater Toronto area.

### CODE REVIEW

**Comment by mampfes** [comment]
Please add documentation and add links in README.md and info.md

https://github.com/mampfes/hacs_waste_collection_schedule#how-to-add-new-sources

**Comment by constvariable** [comment]
Added toronto_ca.md and updated README.md

**Comment by constvariable** [comment]
Added info.md as well

**Comment by mampfes** [comment]
Thanks for your contribution. First source for Canada, great!!!

**Pull request merged**
