### PR TITLE
Update zva_wmk_de.py

### PR DESCRIPTION
**Pull request by buzzibaer**
URL changed in 2024 for ZVA WMK

### CODE REVIEW

**Comment by 5ila5** [comment]
I'm closing this for #1862 as this approach might survive a change back to a ULR style, including the year.

**Comment by buzzibaer** [comment]
I might missing something here, but there is a <?> in the URL now.
Is this reflected in your change?
You might want to look at my pic:

2024-03-05 07_18_07-Update zva_wmk_de py by buzzibaer · Pull Request #1859 · mampfes_hacs_waste_coll

**Comment by 5ila5** [comment]
I do not see the year as a parameter in the request. So I'm not sure what you mean. The `?` initializes the GET parameter section and is not part of the URL, The `params` argument sets a `?` at the end and encodes the parameters correctly.

e.g https://www.zva-wmk.de/termine/schnellsuche?city=BERKATAL_FRANKENHAIN&street=Lindenstra%25C3%259Fe&type=Biom%25C3%25BCll&link=ical&timestart=6&timeend=17&reminder=1440&display=0

`?` initializes parameter section separated by `&`

**Comment by buzzibaer** [comment]
you are right!
:)

/closed

**Pull request closed without merging**
