### PR TITLE
Double quotes caused error with f-string

### PR DESCRIPTION
**Pull request by morotsgurka**
This fixes the error i wrote about in pull request #2335 
The problem in ahk_heidekreis_de caused the update_docu_links.py to fail

### CODE REVIEW

**Comment by 5ila5** [comment]
Thanks, this double quotes only works for python 3.12 so it's probably best to not do this

**Comment by morotsgurka** [comment]
Oh okay, i was using 3.10. Why is python-version file ignored by gitignore? Would make it easier with pyenv to use the "correct" version of python

**Comment by 5ila5** [comment]
I don't really think there is a "correct" version of python, I think containing some backwards compatibility is probably a good thing, I honestly did not see that when merging, and I do not really test against older version of python. I think people should probably be able to use older (still maintained) versions of python like 3.10 for simple source development (even though HA dropped support for 3.11 in 2024.4)

**Comment by morotsgurka** [comment]
With "correct" i meant a known working version. Everything above 3.9 seems to work right now but the docs never mention anything about which version of python to use. Maybe it could help someone if they use for example 3.9 and don't understand why the script wont work.
Maybe a simple "requirements" section in the contributing docs with quick start like:
- Install python 3.10 or higher
- Install dependencies with pip install -r requirements.txt
- Test a source: python3 custom_components/waste_collection_schedule/waste_collection_schedule/test/test_sources.py -s edpevent_se -i -t
- Create a fork
- Create branch
etc?

**Pull request merged**
