### PR TITLE
Change ICS split_at to use regex, and make casing uniform.

### PR DESCRIPTION
**Pull request by cpw**
The ICS split feature is a great idea, but for maximum functionality, it should use a regular expression based split string instead of a plain delimiter.

My garbage has summary lines as follows:
```SUMMARY:Garbage\, green bin\, yard trimmings\, and blue bin
SUMMARY:Yard trimmings\, green bin\, and black bin
SUMMARY:Garbage\, green bin\, yard trimmings\, and blue bin
SUMMARY:Black bin\, yard trimmings\, and green bin
SUMMARY:Garbage\, blue bin\, green bin\, and yard trimmings
SUMMARY:Black bin\, green bin\, and yard trimmings
SUMMARY:Garbage\, blue bin\, yard trimmings\, and green bin
SUMMARY:Black bin\, green bin\, and yard trimmings
SUMMARY:Garbage\, green bin\, yard trimmings\, and blue bin
SUMMARY:Green bin\, yard trimmings\, and black bin
SUMMARY:Garbage\, blue bin\, green bin\, and yard trimmings
SUMMARY:Green bin\, yard trimmings\, and black bin
SUMMARY:Garbage\, yard trimmings\, green bin\, and blue bin
SUMMARY:Black bin\, yard trimmings\, and green bin
SUMMARY:Garbage\, blue bin\, green bin\, and yard trimmings
SUMMARY:Green bin\, yard trimmings\, and black bin
SUMMARY:Green bin
```

So it really needs a bit of processing to handle it and make uniform categories. Using a regular expression for splitting:
```
        split_at: "\\, [and ]*"
```
allows me to make uniform strings out of the summary lines. using `.capitalize` allows me to turn everything into a uniform case. (lower or upper would probably work fine as well).

I end up with garbage in 5 categories:
* Garbage
* Blue bin
* Green bin
* Black bin
* Yard trimmings

This seems to be the minimal change to allow this to work. Note that this ICS is actually from recollect, so by doing this, you'd probably allow ALL recollect ICS calendars to work pretty nicely.

### CODE REVIEW

**Comment by mampfes** [comment]
Thanks for your contribution. And thanks for the hint wir recollect! Do you have a running example that you could add in the ics.md? I think this would be very helpful for others.

**Comment by cpw** [comment]
Hi. Here's how you do it:

I'm in Ottawa, so I visit https://api.recollect.net/r/area/Ottawa and enter my address. Click "get a calendar" then "Add to iCal". Finally, the URL under "Subscribe to calendar" is your ICS calendar link.

webcal://recollect.a.ssl.fastly.net/api/places/BCCDF30E-578B-11E4-AD38-5839C200407A/services/208/events.en.ics?client_id=6FBD18FE-167B-11EC-992A-C843A7F05606

You can strip the client ID and change the protocol to https, and you have a valid ICS URL.

```
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: "https://recollect.a.ssl.fastly.net/api/places/BCCDF30E-578B-11E4-AD38-5839C200407A/services/208/events.en.ics"
        split_at: "\\, [and ]*"
      customize:
        - type: Garbage
          icon: mdi:trash-can
        - type: Green bin
          icon: mdi:leaf
        - type: Blue bin
          icon: mdi:recycle
        - type: Black bin
          icon: mdi:recycle
```

This is a valid working waste schedule for ICS. Note that the raw ICS has the problems outlined above, but the regex split_at and .capitalize fixes it nicely.

**Comment by amacdonel** [comment]
Hi,
Where I'm located there are some weeks I have collections that don't have a comma in them, like this:

SUMMARY:Green bin and recycling
SUMMARY:Garbage\, green bin\, and recycling
SUMMARY:Green bin and recycling
SUMMARY:Garbage\, green bin\, and recycling
SUMMARY:Green bin and recycling
SUMMARY:Garbage\, green bin\, and recycling

I'm struggling with the regex, using an online regex editor I came up with `(, [and ]*)|( and )`
but when I add it to the split_at command: `split_at: "\\(\\, [and ]*\\)\\|\\( and \\)"` it doesn't split the strings and in the ICS calendar I see the full strings for each day.

Any tips or suggestions on how to split this data?

**Comment by amacdonel** [comment]
For refence to others that might see this, an innelegant solution I came up with (if no option is found later) was using the regex variable to remove commas and then split on spaces. I ended up with entries for "Green" and "Bin" but this was corrected on the sensors:

```
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: https://recollect.a.ssl.fastly.net/api/places/<guid>/services/193/events.en.ics
        regex: "\\,"
        split_at: " "
      customize:
        - type: Garbage
          icon: mdi:trash-can
        - type: Green
          alias: Green Bin
          icon: mdi:leaf
        - type: Recycling
          icon: mdi:recycle

sensor:
  - platform: waste_collection_schedule
    name: waste_garbage
    types:
      - Garbage
      - Garbage,

  - platform: waste_collection_schedule
    name: waste_greenbin
    types:
      - Green Bin

  - platform: waste_collection_schedule
    name: waste_recycling
    types:
      - Recycling
```

**Pull request merged**
