### PR TITLE
Added Abfall Zollernalbkreis service provider

### PR DESCRIPTION
**Pull request by atrox06**
Added Abfall Zollernalbkreis service provider

### CODE REVIEW

**Comment by mampfes** [comment]
Thanks!

**Comment by h4nnes** [comment]
Hi @atrox06 ,
Is this still working for you? Seems Zollernalbkreis is using abfall.io now?! But I only get an key and housenumber back:

https://www.zollernalbkreis.de/landratsamt/aemter++und+organisation/Elektronischer+Abfallkalender

**Comment by atrox06** [comment]
Hi @h4nnes @mampfes, 
You're right, the Zollernalbkreis seems to be using Abfall.io now. However, the variables in the browser debug look completely different from those in the Abfall.io service. Does the service need to be adapted?

These are the values I see in the get request:
key
	c43bab652cbb25fa84ed515dcfeb9093
mode
	export
idhousenumber
	11115
wastetypes
	50,17,48,19,31
timeperiod
	20240101-20241231

**Comment by h4nnes** [comment]
Yes, I also only got the Key and housenumber. Seems this is different and they don’t send the „Komune“.

That’s why I switched to the ICS (just use the link to the ICS in the component and replace the fix year with a variable in the Url).

**Comment by Bock93** [comment]
> Yes, I also only got the Key and housenumber. Seems this is different and they don’t send the „Komune“.
> 
> That’s why I switched to the ICS (just use the link to the ICS in the component and replace the fix year with a variable in the Url).

Hi h4nnes,

Could you give an explanation how to adapt the source, since it isn't working anymore on my side. If I follow the description from the source (on github) I cant fetch any data for 2024. 
The link mentioned in the description (https://www.abfallkalender-zak.de/) seems to be not up-to-date. Atleast you can't choose 2024 as an option.

How did you import the new ICS? I went to "https://www.zollernalbkreis.de/landratsamt/aemter++und+organisation/Elektronischer+Abfallkalender" and posted my information there. This way I got an actual ICS file for my adress, but how do you import the ICS file? How do I have to change my conf.yaml entry for the source?

Thank you!

**Comment by h4nnes** [comment]
> > Yes, I also only got the Key and housenumber. Seems this is different and they don’t send the „Komune“.
> > That’s why I switched to the ICS (just use the link to the ICS in the component and replace the fix year with a variable in the Url).
> 
> Hi h4nnes,
> 
> Could you give an explanation how to adapt the source, since it isn't working anymore on my side. If I follow the description from the source (on github) I cant fetch any data for 2024. The link mentioned in the description (https://www.abfallkalender-zak.de/) seems to be not up-to-date. Atleast you can't choose 2024 as an option.
> 
> How did you import the new ICS? I went to "https://www.zollernalbkreis.de/landratsamt/aemter++und+organisation/Elektronischer+Abfallkalender" and posted my information there. This way I got an actual ICS file for my adress, but how do you import the ICS file? How do I have to change my conf.yaml entry for the source?
> 
> Thank you!

Hi Bock93,
Yes, I also used the new link from https://www.zollernalbkreis.de/landratsamt/aemter++und+organisation/Elektronischer+Abfallkalender to get the ICS. You just need to fill your data and then right click on the "Export ICS" button and copy the url and use it like this:

`waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: https://api.abfall.io/?key=xxx&mode=export&idhousenumber=1212&wastetypes=50,17,19,31&timeperiod={%Y}0101-{%Y}1231&showinactive=false&type=ics
#          - 50 #Biomüll
#          - 17 #Gelbersack
#          - 19 #Papiertonne
#          - 31 #Restmüll
      calendar_title: Abfallkalender Salmendingen`

Just replace the year in the link with {%Y} --> so it should hopefully get every year the correct ICS file

**Pull request merged**
