### PR TITLE
New Source: North Kesteven, UK

### PR DESCRIPTION
**Pull request by dt215git**
New source, as requested in #986 

```bash
Testing source n-kesteven_org_uk ...
  found 3 entries for Test_001
    2023-05-30 : Black (Domestic) [mdi:trash-can]
    2023-05-23 : Green (Recycling) [mdi:recycle]
    2023-06-06 : Purple (Paper/Card) [mdi:newspaper]
  found 4 entries for Test_002
    2023-05-31 : Black (Domestic) [mdi:trash-can]
    2023-05-24 : Green (Recycling) [mdi:recycle]
    2023-06-07 : Purple (Paper/Card) [mdi:newspaper]
    2023-05-24 : Brown (Garden Waste) [mdi:leaf]
  found 4 entries for Test_003
    2023-06-02 : Black (Domestic) [mdi:trash-can]
    2023-05-26 : Green (Recycling) [mdi:recycle]
    2023-06-09 : Purple (Paper/Card) [mdi:newspaper]
    2023-05-25 : Brown (Garden Waste) [mdi:leaf]
  found 3 entries for Test_004
    2023-05-27 : Black (Domestic) [mdi:trash-can]
    2023-06-19 : Green (Recycling) [mdi:recycle]
    2023-06-05 : Purple (Paper/Card) [mdi:newspaper]
```

### CODE REVIEW

**Review by 5ila5 — COMMENTED** [review]
It might not be a problem but all other sources follow the nameing scheme without `-` I think we should keep it that way and replace it with `_`.

**Comment by dt215git** [comment]
Good point, although I'd be inclined to change it to `north_kesteven`. It follows the convention but has more readability than simply `n_kesteven`.

**Comment by dt215git** [comment]
```bash
Testing source north_kesteven_org_uk ...
  found 3 entries for Test_001
    2023-05-30 : Black (Domestic) [mdi:trash-can]
    2023-06-20 : Green (Recycling) [mdi:recycle]
    2023-06-06 : Purple (Paper/Card) [mdi:newspaper]
  found 4 entries for Test_002
    2023-05-31 : Black (Domestic) [mdi:trash-can]
    2023-06-21 : Green (Recycling) [mdi:recycle]
    2023-06-07 : Purple (Paper/Card) [mdi:newspaper]
    2023-06-07 : Brown (Garden Waste) [mdi:leaf]
  found 4 entries for Test_003
    2023-06-02 : Black (Domestic) [mdi:trash-can]
    2023-05-26 : Green (Recycling) [mdi:recycle]
    2023-06-09 : Purple (Paper/Card) [mdi:newspaper]
    2023-05-25 : Brown (Garden Waste) [mdi:leaf]
  found 3 entries for Test_004
    2023-05-27 : Black (Domestic) [mdi:trash-can]
    2023-06-19 : Green (Recycling) [mdi:recycle]
    2023-06-05 : Purple (Paper/Card) [mdi:newspaper]
```

**Comment by 5ila5** [comment]
thanks for your contribution

**Pull request merged**
