### PR TITLE
allow to use other fields than summary in ical source for event title

### PR DESCRIPTION
**Pull request by splattner**
My city uses the Location field in the ical calendar to spererate between different areas while having the same summary. So I need to use the location for distinction

### CODE REVIEW

**Comment by mampfes** [comment]
Interesting enhancement! Instead of specifying title and separator, I would prefer to specify a format string like the `value_template` in the sensor configuration.

Example:
```yaml
  value_template: '{{summary}} {{location}}'
```

Do you think this is feasible?

**Comment by splattner** [comment]
Alright, I finally found some time to implement this using template. What do you thing?

**Comment by splattner** [comment]
is there anything I can help or change to get this merged?

**Comment by splattner** [comment]
Anything I can do to get this merged? Or no interest?

**Comment by mampfes** [comment]
> Anything I can do to get this merged? Or no interest?

Oh, sorry I missed that! Thanks for your contribution. LGTM
@5ila5 Do want to merge it?

**Comment by 5ila5** [comment]
Looks good I added jinja2 to requirements.txt and fixed a spelling error in the ICS.md file

Thanks for your contribution

**Pull request merged**
