### PR TITLE
add sector27

### PR DESCRIPTION
**Pull request by lubeda**
add a regional provider in the region Kreis Recklinghausen.

available for at least the cities of Datteln, Marl, Oer-Erkenschwick.

sadly you can get the arguments for the function only by "hacking" the webpage. see sector27_de.md

### CODE REVIEW

**Review by mampfes — COMMENTED** [review]
The .py file ist empty.

**Comment by lubeda** [comment]
sector27_de.py is now available. Sorry

**Comment by mampfes** [comment]
Why did you use the month based query? I would prefer the year based query because it requires only 1 request (or 2 at the end of a year - see examples in other sources). This probably produces less load on the server side.

**Comment by lubeda** [comment]
Made the fetchrange as option! "month" is better for me (fewer calendarentries), year is better for the server (fewer requests). I stay with "month" as default.

**Comment by mampfes** [comment]
Could you describe your actual need regarding the calendar entries. Why do you want to limit the calendar entries?

Or do you want to limit the number of entries in the sensors? If yes, there are already options to do that.

**Comment by lubeda** [comment]
from the automation point of view i only need the next event of a kind. 
from the planing aspect i need only the next 2-3 events to decide when to cleanup the garden, 
from the storage/memory of my HA instance aspect the fewer events is better.
for me there is no usecase of having one year in advance in my system. But that depends on the point of view.

**Comment by mampfes** [comment]
Do you have a link for the cities of Dorsten, Schermbeck and Raesfeld to get the magic numbers? I didn't find one on their homepages.

**Comment by lubeda** [comment]
After contact to the provider there is no possibility get access to the data yet. Could you remove the the sector27_de branch.

**Comment by mampfes** [comment]
Why do you want to remove the whole source for sector 27? I think it is still useful, even if it doesn't support all cities. Therefore I would like to keep it.

**Comment by lubeda** [comment]
Of course it is useful but there was a dispute with sector27. They don't like the way i used their data and they blocked the access from within home-assistant. Although there is another "hack" to still get the data, i gave up. So i delete the repository :-(

**Comment by mampfes** [comment]
Just in case you didn't notice: I added sector27_de source in release 1.7.0 - including a fix for the blocked access. And I also changed to source attributes to city and street. Thereby it becomes easier for the user to configure the source. I try to use this schema in all new sources (instead of magic numbers which have to be extracted from the internals of the web page).

**Comment by RufusRed80** [comment]
Please excuse my bad English, does it still work with the source sector 27 (Stadt Datteln) or has it been discontinued for good? I can't get it to run. 
Or is there another way?

**Comment by lubeda** [comment]
Hi, bei mir läuft "Datteln" ohne Probleme. Hast Du eine Fehlermeldung oder einen Logeintrag?

**Comment by RufusRed80** [comment]
Hi @lubeda 

ich bekomme mit dem Eintrag 

`waste_collection_schedule:
  sources:
    - name: sector27_de
      args:
        city: Datteln
        street: Eichenstrasse`

Nur diesen Zustand zurück:
Screenshot 2023-08-05 110041

Auch wenn ich die street auf Eichenstraße ändere, ändert sich nichts :(

**Comment by lubeda** [comment]
Versuch mal diesen Eintrag mit **ß**

```
waste_collection_schedule:
  sources:
    - name: sector27_de
      args:
        city: Datteln
        street: "Eichenstraße"
      calendar_title: Müllkalender
```

Die API reagiert nur auf **ß**

**Comment by RufusRed80** [comment]
Vielen vielen Dank! Mit Deinem Code funktioniert es, obwohl ich es auch mit **ß** versucht habe . Lag es am fehlenden "      calendar_title: Müllkalender"?

**Comment by lubeda** [comment]
Nö, der `calendar_title` hat nichts damit zu tun. Hast Du einen Mac? Ich glaube, es funktioniert, nur wenn das ß in Unicode gespeichert wird. Bei meinem Windows hat es direkt funktioniert.

**Comment by RufusRed80** [comment]
> Nö, der `calendar_title` hat nichts damit zu tun. Hast Du einen Mac? Ich glaube, es funktioniert, nur wenn das ß in Unicode gespeichert wird. Bei meinem Windows hat es direkt funktioniert.
Nein, bin auch Windows-User. Aber sei´s drum, es funktioniert nun perfekt. DANKE!

**Pull request merged**
