### PR TITLE
Update chiltern_gov_uk.py

### PR DESCRIPTION
**Pull request by craigsblackie**
This should fix the source after it was changed.

### CODE REVIEW

**Comment by 5ila5** [comment]
Thanks for your work,
I would really like it to be an extra itouchvision source so it's easy to integrate potential other municipalities using this "new" itouchvision API I know NEWPORT does use this by default, but we could use the old implementation with the same ID

Do you want to give it a try or should I redo the source to a dedicated second itouchvion source?

**Comment by craigsblackie** [comment]
It would make sense if other councils are usig this new endpoint to create a new generic itouchvision source. I'm not sure I have the time to implement this currently, but hopefully this provides a solid base from which to build that. 

Why would they encrypt the parameters?!

**Comment by 5ila5** [comment]
Ok I will do the new source

I have no clue why they do this, maybe it's some react library they are using the key's name is REACT_APP_ENCRYPT_PUBLIC_KEY

**Comment by 5ila5** [comment]
Closed for #2522

**Pull request closed without merging**
