### PR TITLE
Change Mannheim from AppAbfallplus to ics

### PR DESCRIPTION
**Pull request by ReneNulschDE**
This is to fix issue: #1682 

- Remove Mannheim from AppAbfallplus
- Add new source mannheim_de (copy of offenbach_de, without wizard)
- Add new doc source mannheim_de

### CODE REVIEW

**Comment by 5ila5** [comment]
As this does not implement anything you couldn't do with the generic ICS source, I would prefer providing documentation for the ICS source for Mannheim ([guide](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/contributing_ics.md))

**Comment by derDeno** [comment]
Maybe it would make sense to implement insert-it as a new platform.
As there are multiple cities using this platform and they all work the same way, it would make sense to implement a wizard.

The wizard could use the app id to obtain the API base url and using two other API calls it's possible to generate the street ID and the location ID.

**Comment by derDeno** [comment]
@5ila5 I understand what you mean. Personally, I'd prefer a simple wizard that keeps track of all the insert-it apps and eliminates even the few clicks needed for the ics link. But yes, I can see why it would also make sense to keep things simpler

**Comment by 5ila5** [comment]
closing this for #1717
@ReneNulschDE Thanks for your efforts anyway

**Pull request closed without merging**
