### PR TITLE
New Source: UK Bin Collection Data Project

### PR DESCRIPTION
**Pull request by dt215git**
The [UK Bin Collection Data](https://github.com/robbrad/UKBinCollectionData) project have standardised the json output from their scripts. This script can take one of the json files as an input, much like the ics/ical source.

A service script is also included that can generate new json files for testing purposes.

```bash
Testing source ukbcd ...
  found 288 entries for Test_File
    2023-01-05 : Refuse [None]
    2023-01-12 : Paper & Cardboard [None]
    2023-01-20 : Garden [None]
    2023-01-09 : Refuse [None]
    2023-02-09 : Refuse [None]
    2023-02-15 : Recycling [None]
    2023-02-16 : Paper & Cardboard [None]
    2023-02-14 : Refuse [None]
    2023-03-22 : Food [None]
    2023-03-20 : Refuse [None]
    2023-03-06 : Food [None]
    2023-03-27 : Food [None]
    2023-04-26 : Refuse [None]
    2023-04-01 : Food [None]
    2023-04-10 : Food [None]
    2023-04-19 : Paper & Cardboard [None]
    2023-05-22 : Recycling [None]
    2023-05-17 : Food [None]
    2023-05-03 : Batteries [None]
    2023-05-16 : Refuse [None]
    2023-06-10 : Garden [None]
    2023-06-21 : Garden [None]
    2023-06-21 : Refuse [None]
    2023-06-26 : Paper & Cardboard [None]
    2023-07-24 : Paper & Cardboard [None]
    2023-07-05 : Refuse [None]
    2023-07-12 : Batteries [None]
    2023-07-18 : Garden [None]
    2023-08-09 : Recycling [None]
    2023-08-22 : Recycling [None]
    2023-08-11 : Food [None]
    2023-08-23 : Food [None]
    2023-09-20 : Recycling [None]
    2023-09-08 : Garden [None]
    2023-09-08 : Food [None]
    2023-09-22 : Recycling [None]
    2023-10-10 : Refuse [None]
    2023-10-09 : Refuse [None]
    2023-10-20 : Refuse [None]
    2023-10-02 : Food [None]
    2023-11-18 : Refuse [None]
    2023-11-16 : Paper & Cardboard [None]
    2023-11-21 : Recycling [None]
    2023-11-18 : Recycling [None]
    2023-12-28 : Batteries [None]
    2023-12-22 : Garden [None]
    2023-12-17 : Paper & Cardboard [None]
    2023-12-26 : Paper & Cardboard [None]
    2024-01-28 : Paper & Cardboard [None]
    2024-01-22 : Recycling [None]
    2024-01-06 : Paper & Cardboard [None]
    2024-01-06 : Batteries [None]
    2024-02-27 : Paper & Cardboard [None]
    2024-02-28 : Batteries [None]
    2024-02-01 : Batteries [None]
    2024-02-05 : Garden [None]
    2024-03-17 : Paper & Cardboard [None]
    2024-03-17 : Paper & Cardboard [None]
    2024-03-17 : Food [None]
    2024-03-01 : Food [None]
    2024-04-16 : Paper & Cardboard [None]
    2024-04-05 : Paper & Cardboard [None]
    2024-04-22 : Batteries [None]
    2024-04-20 : Garden [None]
    2024-05-10 : Recycling [None]
    2024-05-27 : Paper & Cardboard [None]
    2024-05-21 : Food [None]
    2024-05-07 : Garden [None]
    2024-06-12 : Refuse [None]
    2024-06-18 : Paper & Cardboard [None]
    2024-06-14 : Food [None]
    2024-06-13 : Garden [None]
    2024-07-18 : Batteries [None]
    2024-07-19 : Recycling [None]
    2024-07-07 : Garden [None]
    2024-07-28 : Batteries [None]
    2024-08-27 : Food [None]
    2024-08-24 : Refuse [None]
    2024-08-02 : Batteries [None]
    2024-08-20 : Refuse [None]
    2024-09-12 : Garden [None]
    2024-09-28 : Recycling [None]
    2024-09-21 : Batteries [None]
    2024-09-04 : Refuse [None]
    2024-10-28 : Food [None]
    2024-10-24 : Batteries [None]
    2024-10-08 : Paper & Cardboard [None]
    2024-10-16 : Garden [None]
    2024-11-25 : Food [None]
    2024-11-01 : Garden [None]
    2024-11-07 : Batteries [None]
    2024-11-28 : Food [None]
    2024-12-17 : Paper & Cardboard [None]
    2024-12-11 : Recycling [None]
    2024-12-25 : Batteries [None]
    2024-12-17 : Refuse [None]
    2025-01-22 : Paper & Cardboard [None]
    2025-01-01 : Paper & Cardboard [None]
    2025-01-28 : Paper & Cardboard [None]
    2025-01-13 : Food [None]
    2025-02-16 : Food [None]
    2025-02-02 : Garden [None]
    2025-02-01 : Garden [None]
    2025-02-15 : Refuse [None]
    2025-03-21 : Food [None]
    2025-03-15 : Paper & Cardboard [None]
    2025-03-07 : Garden [None]
    2025-03-12 : Recycling [None]
    2025-04-27 : Batteries [None]
    2025-04-22 : Paper & Cardboard [None]
    2025-04-16 : Garden [None]
    2025-04-07 : Refuse [None]
    2025-05-10 : Garden [None]
    2025-05-19 : Refuse [None]
    2025-05-12 : Batteries [None]
    2025-05-05 : Food [None]
    2025-06-10 : Recycling [None]
    2025-06-01 : Refuse [None]
    2025-06-08 : Refuse [None]
    2025-06-05 : Food [None]
    2025-07-07 : Refuse [None]
    2025-07-01 : Recycling [None]
    2025-07-15 : Recycling [None]
    2025-07-25 : Refuse [None]
    2025-08-20 : Garden [None]
    2025-08-25 : Food [None]
    2025-08-16 : Recycling [None]
    2025-08-16 : Paper & Cardboard [None]
    2025-09-25 : Recycling [None]
    2025-09-01 : Batteries [None]
    2025-09-21 : Garden [None]
    2025-09-08 : Refuse [None]
    2025-10-01 : Recycling [None]
    2025-10-28 : Paper & Cardboard [None]
    2025-10-12 : Paper & Cardboard [None]
    2025-10-26 : Paper & Cardboard [None]
    2025-11-15 : Batteries [None]
    2025-11-08 : Food [None]
    2025-11-01 : Batteries [None]
    2025-11-07 : Batteries [None]
    2025-12-07 : Batteries [None]
    2025-12-23 : Batteries [None]
    2025-12-12 : Garden [None]
    2025-12-12 : Garden [None]
    2026-01-12 : Recycling [None]
    2026-01-26 : Batteries [None]
    2026-01-19 : Refuse [None]
    2026-01-22 : Recycling [None]
    2026-02-03 : Batteries [None]
    2026-02-04 : Paper & Cardboard [None]
    2026-02-18 : Recycling [None]
    2026-02-14 : Garden [None]
    2026-03-10 : Food [None]
    2026-03-26 : Batteries [None]
    2026-03-13 : Recycling [None]
    2026-03-18 : Recycling [None]
    2026-04-05 : Food [None]
    2026-04-06 : Batteries [None]
    2026-04-15 : Refuse [None]
    2026-04-16 : Food [None]
    2026-05-23 : Refuse [None]
    2026-05-09 : Batteries [None]
    2026-05-14 : Refuse [None]
    2026-05-13 : Food [None]
    2026-06-09 : Recycling [None]
    2026-06-20 : Recycling [None]
    2026-06-06 : Recycling [None]
    2026-06-28 : Garden [None]
    2026-07-13 : Batteries [None]
    2026-07-15 : Food [None]
    2026-07-17 : Batteries [None]
    2026-07-02 : Refuse [None]
    2026-08-04 : Garden [None]
    2026-08-06 : Paper & Cardboard [None]
    2026-08-01 : Batteries [None]
    2026-08-13 : Recycling [None]
    2026-09-09 : Batteries [None]
    2026-09-06 : Food [None]
    2026-09-28 : Food [None]
    2026-09-12 : Refuse [None]
    2026-10-17 : Batteries [None]
    2026-10-23 : Batteries [None]
    2026-10-09 : Refuse [None]
    2026-10-18 : Paper & Cardboard [None]
    2026-11-15 : Recycling [None]
    2026-11-05 : Batteries [None]
    2026-11-03 : Recycling [None]
    2026-11-08 : Recycling [None]
    2026-12-23 : Batteries [None]
    2026-12-10 : Refuse [None]
    2026-12-05 : Refuse [None]
    2026-12-03 : Garden [None]
    2027-01-28 : Paper & Cardboard [None]
    2027-01-21 : Paper & Cardboard [None]
    2027-01-15 : Paper & Cardboard [None]
    2027-01-17 : Refuse [None]
    2027-02-24 : Recycling [None]
    2027-02-09 : Garden [None]
    2027-02-03 : Paper & Cardboard [None]
    2027-02-14 : Batteries [None]
    2027-03-21 : Refuse [None]
    2027-03-08 : Food [None]
    2027-03-27 : Refuse [None]
    2027-03-28 : Refuse [None]
    2027-04-18 : Paper & Cardboard [None]
    2027-04-21 : Recycling [None]
    2027-04-06 : Paper & Cardboard [None]
    2027-04-08 : Paper & Cardboard [None]
    2027-05-16 : Recycling [None]
    2027-05-13 : Paper & Cardboard [None]
    2027-05-28 : Food [None]
    2027-05-07 : Paper & Cardboard [None]
    2027-06-15 : Paper & Cardboard [None]
    2027-06-27 : Batteries [None]
    2027-06-10 : Refuse [None]
    2027-06-18 : Recycling [None]
    2027-07-19 : Paper & Cardboard [None]
    2027-07-03 : Batteries [None]
    2027-07-26 : Refuse [None]
    2027-07-17 : Refuse [None]
    2027-08-23 : Garden [None]
    2027-08-17 : Garden [None]
    2027-08-13 : Batteries [None]
    2027-08-22 : Batteries [None]
    2027-09-13 : Batteries [None]
    2027-09-01 : Paper & Cardboard [None]
    2027-09-27 : Refuse [None]
    2027-09-26 : Recycling [None]
    2027-10-03 : Garden [None]
    2027-10-06 : Food [None]
    2027-10-24 : Recycling [None]
    2027-10-16 : Food [None]
    2027-11-13 : Recycling [None]
    2027-11-15 : Paper & Cardboard [None]
    2027-11-23 : Recycling [None]
    2027-11-10 : Paper & Cardboard [None]
    2027-12-02 : Batteries [None]
    2027-12-14 : Batteries [None]
    2027-12-27 : Recycling [None]
    2027-12-01 : Recycling [None]
    2028-01-19 : Paper & Cardboard [None]
    2028-01-12 : Garden [None]
    2028-01-23 : Paper & Cardboard [None]
    2028-01-08 : Food [None]
    2028-02-27 : Recycling [None]
    2028-02-12 : Food [None]
    2028-02-23 : Refuse [None]
    2028-02-14 : Food [None]
    2028-03-09 : Garden [None]
    2028-03-21 : Paper & Cardboard [None]
    2028-03-10 : Recycling [None]
    2028-03-16 : Refuse [None]
    2028-04-18 : Paper & Cardboard [None]
    2028-04-03 : Recycling [None]
    2028-04-27 : Refuse [None]
    2028-04-28 : Garden [None]
    2028-05-27 : Recycling [None]
    2028-05-06 : Recycling [None]
    2028-05-04 : Food [None]
    2028-05-19 : Recycling [None]
    2028-06-06 : Recycling [None]
    2028-06-12 : Refuse [None]
    2028-06-12 : Recycling [None]
    2028-06-24 : Refuse [None]
    2028-07-03 : Paper & Cardboard [None]
    2028-07-15 : Paper & Cardboard [None]
    2028-07-10 : Paper & Cardboard [None]
    2028-07-06 : Refuse [None]
    2028-08-07 : Batteries [None]
    2028-08-01 : Refuse [None]
    2028-08-05 : Refuse [None]
    2028-08-19 : Batteries [None]
    2028-09-24 : Recycling [None]
    2028-09-28 : Garden [None]
    2028-09-20 : Recycling [None]
    2028-09-12 : Food [None]
    2028-10-18 : Batteries [None]
    2028-10-06 : Recycling [None]
    2028-10-08 : Food [None]
    2028-10-05 : Refuse [None]
    2028-11-04 : Batteries [None]
    2028-11-10 : Recycling [None]
    2028-11-17 : Garden [None]
    2028-11-07 : Paper & Cardboard [None]
    2028-12-21 : Food [None]
    2028-12-17 : Refuse [None]
    2028-12-18 : Recycling [None]
    2028-12-01 : Batteries [None]
```

### CODE REVIEW

**Comment by mampfes** [comment]
It is ok for me to add this as an additional source.

What's really unfortunate is that multiple projects do the same and cannot benefit from each other. My share in this misery is this I didn't create a separate Python package at the very beginng which hosts the sources. With that, (at least) every Python project could benefit from the enormous work...

**Comment by 5ila5** [comment]
What about a real integration and adding [uk-bin-collection](https://pypi.org/project/uk-bin-collection/) to dependencies? You can get the data like this.

```python
from uk_bin_collection.uk_bin_collection.collect_data import UKBinCollectionApp

def main():
    app = UKBinCollectionApp()
    module_str = "DoncasterCouncil"
    module = app.get_council_module(module_str)
    data = app.client_code(
            get_bin_data_class=module.CouncilClass(),
            address_url="https://www.doncaster.gov.uk/Compass/Entity/Launch/D3/",
            postcode=None,
            paon=None,
            uprn=100050768956,
            skip_get_url=True,
            dev_mode=False,
            council_module_str=module_str,
        )
    print(data)
```

 The only problem would be how to get which council needs which parameters. They take this information from  [UKBinCollectionData/uk_bin_collection/tests/input.json](https://github.com/robbrad/UKBinCollectionData/blob/master/uk_bin_collection/tests/input.json) for generating their wiki. but it's not part of the package we could add all parameters as optional and let the user look it up in the UKBinCollectionApp wiki.

**Comment by mampfes** [comment]
Ah, now I see your point. I like the idea!

Regarding the json file: The source could also download the current json file from github and use then use the values to map a council to uprn/... whatever.

**Comment by mogusbi** [comment]
Any updates on this? Would love to see it added in order to finally get North Tyneside council bin dates added

**Comment by dt215git** [comment]
@mampfes, @5ila5

I opted for reading the UKBCD json output for a couple of reasons:
- A lot of the UKBCD scripts use Selenium to interact with the source websites. Looking at the HA forum, getting Selenium/webdrivers to work within HA isn't trivial. Given we have no control over which flavour of HA people are using, it seemed safer to push the burden of getting the json onto the end user where they can implement the UKBCD scripts is whatever way fits their environment
- It makes a cleaner break between who's responsible for what when issues occur.
  - UKBCD is querying the website and returning a schedule in json format.
  -  WCS is reading a provided json and making that info available to sensors/calendars.

Embedding UKBCD into WCS would be nice from an end users perspective, but may lead to a lot of issues where all we can say is "You'll need to get UKBCD to fix things"

That said, they now seem to have their own [HACS custom component](https://github.com/robbrad/UKBinCollectionData#install-with-hacs-recommended), so maybe this PR is no longer needed.

**Comment by 5ila5** [comment]
I took a more detailed look and I would agree that implementing it my proposed way is probably a bad idea. I will merge this as this provides additional features not found in the [UKBinCollectionData](https://github.com/robbrad/UKBinCollectionData) HA component

**Pull request merged**
