### PR TITLE
Add uttlesford_gov_uk

### PR DESCRIPTION
**Pull request by dearlove**
Added uttlesford_gov_uk sources file, documentation file and updated info.md and README.md
Tested by manually adding files to home assistant.
Output of test_sources.py:
Testing source uttlesford_gov_uk ...
  found 6 entries for Brook Cottage, CM6 1LW
    2023-03-07: Green (Recycling) and Brown (Food) [mdi:recycle]
    2023-03-14: Black (Non-Recyclable) and Brown (Food) [mdi:trash-can]
    2023-03-21: Green (Recycling) and Brown (Food) [mdi:recycle]
    2023-03-28: Black (Non-Recyclable) and Brown (Food) [mdi:trash-can]
    2023-04-04: Green (Recycling) and Brown (Food) [mdi:recycle]
    2023-04-11: Black (Non-Recyclable) and Brown (Food) [mdi:trash-can]

### CODE REVIEW

**Comment by mampfes** [comment]
Wouldn't it be better to separate the 3 different collection types? black + brown + green

**Comment by dearlove** [comment]
Hi,  happy to separate it out if you would prefer. The reason I didn’t is that the website doesn’t list them separately and the brown food bin is every week with another collection so if you just looked for the next collection in home assistant it would potentially only show either green or brown but not both. But happy to separate them out of you think that’s the better option. Thanks. On 1 Mar 2023, at 18:03, Steffen Zimmermann ***@***.***> wrote:﻿
Wouldn't it be better to separate the 3 different collection types? black + brown + green

**Comment by mampfes** [comment]
Yes, I would prefer to separate it. I think we have some similar examples and always separated it. This allows the user to setup sensors for each individual waste type.

**Comment by dearlove** [comment]
OK I've seperated them out so each returns as a separate collection entry.
New test output:
Testing source uttlesford_gov_uk ...
  found 12 entries for Brook Cottage, CM6 1LW
    2023-03-07: Green (Dry Recycling) [mdi:recycle]
    2023-03-07: Brown (Food Waste) [mdi:food-apple]
    2023-03-14: Black (Non-Recyclable) [mdi:trash-can]
    2023-03-14: Brown (Food Waste) [mdi:food-apple]
    2023-03-21: Green (Dry Recycling) [mdi:recycle]
    2023-03-21: Brown (Food Waste) [mdi:food-apple]
    2023-03-28: Black (Non-Recyclable) [mdi:trash-can]
    2023-03-28: Brown (Food Waste) [mdi:food-apple]
    2023-04-04: Green (Dry Recycling) [mdi:recycle]
    2023-04-04: Brown (Food Waste) [mdi:food-apple]
    2023-04-11: Black (Non-Recyclable) [mdi:trash-can]
    2023-04-11: Brown (Food Waste) [mdi:food-apple]
  found 12 entries for Springfields, CM6 1BP
    2023-03-02: Black (Non-Recyclable) [mdi:trash-can]
    2023-03-02: Brown (Food Waste) [mdi:food-apple]
    2023-03-09: Green (Dry Recycling) [mdi:recycle]
    2023-03-09: Brown (Food Waste) [mdi:food-apple]
    2023-03-16: Black (Non-Recyclable) [mdi:trash-can]
    2023-03-16: Brown (Food Waste) [mdi:food-apple]
    2023-03-23: Green (Dry Recycling) [mdi:recycle]
    2023-03-23: Brown (Food Waste) [mdi:food-apple]
    2023-03-30: Black (Non-Recyclable) [mdi:trash-can]
    2023-03-30: Brown (Food Waste) [mdi:food-apple]
    2023-04-06: Green (Dry Recycling) [mdi:recycle]
    2023-04-06: Brown (Food Waste) [mdi:food-apple]

**Comment by mampfes** [comment]
Thanks for your contribution.

**Pull request merged**
