### PR TITLE
Added support for Contarina S.p.A. (it)

### PR DESCRIPTION
**Pull request by Slthy**
Added support for various areas Italian province of Treviso via ics source.

output for: `python test_sources.py -y contarina_it`
```bash
Testing ICS contarina_it
  found 155 entries for Treviso - cintura urbana"
```

output for: `python test_sources.py -y contarina_it -l`
```bash
Testing ICS contarina_it
  found 155 entries for Treviso - cintura urbana"
    2024-10-31 : Treviso - cintura urbana: Vegetale, Umido
    2024-07-31 : Treviso - cintura urbana: Secco
    2024-01-31 : Treviso - cintura urbana: Secco
    2024-10-30 : Treviso - cintura urbana: Carta
    2024-09-30 : Treviso - cintura urbana: VPL, Umido
    2024-05-30 : Treviso - cintura urbana: Vegetale, Umido
    2024-03-30 : Treviso - cintura urbana: VPL, Umido
    2024-08-29 : Treviso - cintura urbana: Vegetale, Umido
    2024-07-29 : Treviso - cintura urbana: VPL, Umido
    2024-05-29 : Treviso - cintura urbana: Carta
    2024-04-29 : Treviso - cintura urbana: VPL, Umido
    2024-02-29 : Treviso - cintura urbana: Vegetale, Umido
    2024-01-29 : Treviso - cintura urbana: VPL, Umido
    2024-11-28 : Treviso - cintura urbana: Vegetale, Umido
    2024-10-28 : Treviso - cintura urbana: VPL, Umido
    2024-08-28 : Treviso - cintura urbana: Secco
    2024-02-28 : Treviso - cintura urbana: Secco
    2024-03-28 : Treviso - cintura urbana: Vegetale, Umido
    2024-11-27 : Treviso - cintura urbana: Carta
    2024-06-27 : Treviso - cintura urbana: Vegetale, Umido
    2024-05-27 : Treviso - cintura urbana: VPL, Umido
    2024-03-27 : Treviso - cintura urbana: Secco
    2024-09-26 : Treviso - cintura urbana: Vegetale, Umido
    2024-08-26 : Treviso - cintura urbana: VPL, Umido
    2024-06-26 : Treviso - cintura urbana: Carta
    2024-02-26 : Treviso - cintura urbana: VPL, Umido
    2024-11-25 : Treviso - cintura urbana: VPL, Umido
    2024-09-25 : Treviso - cintura urbana: Secco
    2024-07-25 : Treviso - cintura urbana: Vegetale, Umido
    2024-03-25 : Treviso - cintura urbana: VPL, Umido
    2024-01-25 : Treviso - cintura urbana: Umido
    2024-10-24 : Treviso - cintura urbana: Vegetale, Umido
    2024-07-24 : Treviso - cintura urbana: Carta
    2024-06-24 : Treviso - cintura urbana: VPL, Umido
    2024-04-24 : Treviso - cintura urbana: Secco
    2024-01-24 : Treviso - cintura urbana: Carta
    2024-12-23 : Treviso - cintura urbana: VPL, Umido
    2024-10-23 : Treviso - cintura urbana: Secco
    2024-09-23 : Treviso - cintura urbana: VPL, Umido
    2024-05-23 : Treviso - cintura urbana: Vegetale, Umido
    2024-08-22 : Treviso - cintura urbana: Vegetale, Umido
    2024-05-22 : Treviso - cintura urbana: Secco
    2024-07-22 : Treviso - cintura urbana: VPL, Umido
    2024-04-22 : Treviso - cintura urbana: VPL, Umido
    2024-02-22 : Treviso - cintura urbana: Umido
    2024-01-22 : Treviso - cintura urbana: VPL, Umido
    2024-11-21 : Treviso - cintura urbana: Vegetale, Umido
    2024-12-21 : Treviso - cintura urbana: Carta
    2024-10-21 : Treviso - cintura urbana: VPL, Umido
    2024-08-21 : Treviso - cintura urbana: Carta
    2024-03-21 : Treviso - cintura urbana: Umido
    2024-02-21 : Treviso - cintura urbana: Carta
    2024-11-20 : Treviso - cintura urbana: Secco
    2024-06-20 : Treviso - cintura urbana: Vegetale, Umido
    2024-05-20 : Treviso - cintura urbana: VPL, Umido
    2024-03-20 : Treviso - cintura urbana: Carta
    2024-12-19 : Treviso - cintura urbana: Vegetale, Umido
    2024-09-19 : Treviso - cintura urbana: Vegetale, Umido
    2024-08-19 : Treviso - cintura urbana: VPL, Umido
    2024-06-19 : Treviso - cintura urbana: Secco
    2024-02-19 : Treviso - cintura urbana: VPL, Umido
    2024-12-18 : Treviso - cintura urbana: Secco
    2024-11-18 : Treviso - cintura urbana: VPL, Umido
    2024-09-18 : Treviso - cintura urbana: Carta
    2024-07-18 : Treviso - cintura urbana: Vegetale, Umido
    2024-03-18 : Treviso - cintura urbana: VPL, Umido
    2024-04-18 : Treviso - cintura urbana: Vegetale, Umido
    2024-01-18 : Treviso - cintura urbana: Vegetale, Umido
    2024-10-17 : Treviso - cintura urbana: Vegetale, Umido
    2024-07-17 : Treviso - cintura urbana: Secco
    2024-06-17 : Treviso - cintura urbana: VPL, Umido
    2024-04-17 : Treviso - cintura urbana: Carta
    2024-01-17 : Treviso - cintura urbana: Secco
    2024-12-16 : Treviso - cintura urbana: VPL, Umido
    2024-10-16 : Treviso - cintura urbana: Carta
    2024-09-16 : Treviso - cintura urbana: VPL, Umido
    2024-05-16 : Treviso - cintura urbana: Vegetale, Umido
    2024-07-15 : Treviso - cintura urbana: VPL, Umido
    2024-05-15 : Treviso - cintura urbana: Carta
    2024-04-15 : Treviso - cintura urbana: VPL, Umido
    2024-02-15 : Treviso - cintura urbana: Vegetale, Umido
    2024-01-15 : Treviso - cintura urbana: VPL, Umido
    2024-11-14 : Treviso - cintura urbana: Vegetale, Umido
    2024-10-14 : Treviso - cintura urbana: VPL, Umido
    2024-08-14 : Treviso - cintura urbana: Secco
    2024-03-14 : Treviso - cintura urbana: Vegetale, Umido
    2024-02-14 : Treviso - cintura urbana: Secco
    2024-11-13 : Treviso - cintura urbana: Carta
    2024-06-13 : Treviso - cintura urbana: Vegetale, Umido
    2024-05-13 : Treviso - cintura urbana: VPL, Umido
    2024-03-13 : Treviso - cintura urbana: Secco
    2024-12-12 : Treviso - cintura urbana: Vegetale, Umido
    2024-09-12 : Treviso - cintura urbana: Vegetale, Umido
    2024-08-12 : Treviso - cintura urbana: VPL, Umido
    2024-06-12 : Treviso - cintura urbana: Carta
    2024-02-12 : Treviso - cintura urbana: VPL, Umido
    2024-12-11 : Treviso - cintura urbana: Carta
    2024-11-11 : Treviso - cintura urbana: VPL, Umido
    2024-09-11 : Treviso - cintura urbana: Secco
    2024-07-11 : Treviso - cintura urbana: Vegetale, Umido
    2024-04-11 : Treviso - cintura urbana: Vegetale, Umido
    2024-03-11 : Treviso - cintura urbana: VPL, Umido
    2024-01-11 : Treviso - cintura urbana: Vegetale, Umido
    2024-10-10 : Treviso - cintura urbana: Vegetale, Umido
    2024-07-10 : Treviso - cintura urbana: Carta
    2024-06-10 : Treviso - cintura urbana: VPL, Umido
    2024-04-10 : Treviso - cintura urbana: Secco
    2024-01-10 : Treviso - cintura urbana: Carta
    2024-12-09 : Treviso - cintura urbana: VPL, Umido
    2024-10-09 : Treviso - cintura urbana: Secco
    2024-09-09 : Treviso - cintura urbana: VPL, Umido
    2024-05-09 : Treviso - cintura urbana: Vegetale, Umido
    2024-08-08 : Treviso - cintura urbana: Vegetale, Umido
    2024-07-08 : Treviso - cintura urbana: VPL, Umido
    2024-05-08 : Treviso - cintura urbana: Secco
    2024-04-08 : Treviso - cintura urbana: VPL, Umido
    2024-02-08 : Treviso - cintura urbana: Umido
    2024-01-08 : Treviso - cintura urbana: VPL, Umido
    2024-11-07 : Treviso - cintura urbana: Vegetale, Umido
    2024-10-07 : Treviso - cintura urbana: VPL, Umido
    2024-08-07 : Treviso - cintura urbana: Carta
    2024-03-07 : Treviso - cintura urbana: Umido
    2024-02-07 : Treviso - cintura urbana: Carta
    2024-11-06 : Treviso - cintura urbana: Secco
    2024-06-06 : Treviso - cintura urbana: Vegetale, Umido
    2024-05-06 : Treviso - cintura urbana: VPL, Umido
    2024-03-06 : Treviso - cintura urbana: Carta
    2024-12-05 : Treviso - cintura urbana: Vegetale, Umido
    2024-09-05 : Treviso - cintura urbana: Vegetale, Umido
    2024-08-05 : Treviso - cintura urbana: VPL, Umido
    2024-06-05 : Treviso - cintura urbana: Secco
    2024-02-05 : Treviso - cintura urbana: VPL, Umido
    2024-12-04 : Treviso - cintura urbana: Secco
    2024-11-04 : Treviso - cintura urbana: VPL, Umido
    2024-09-04 : Treviso - cintura urbana: Carta
    2024-07-04 : Treviso - cintura urbana: Vegetale, Umido
    2024-05-04 : Treviso - cintura urbana: Carta
    2024-04-04 : Treviso - cintura urbana: Vegetale, Umido
    2024-03-04 : Treviso - cintura urbana: VPL, Umido
    2024-01-04 : Treviso - cintura urbana: Umido
    2024-10-03 : Treviso - cintura urbana: Vegetale, Umido
    2024-07-03 : Treviso - cintura urbana: Secco
    2024-06-03 : Treviso - cintura urbana: VPL, Umido
    2024-04-03 : Treviso - cintura urbana: Carta
    2024-01-03 : Treviso - cintura urbana: Secco
    2024-12-02 : Treviso - cintura urbana: VPL, Umido
    2024-10-02 : Treviso - cintura urbana: Carta
    2024-09-02 : Treviso - cintura urbana: VPL, Umido
    2024-05-02 : Treviso - cintura urbana: Vegetale, Umido
    2024-08-01 : Treviso - cintura urbana: Vegetale, Umido
    2024-07-01 : Treviso - cintura urbana: VPL, Umido
    2024-02-01 : Treviso - cintura urbana: Vegetale, Umido
    2023-12-27 : Treviso - cintura urbana: Carta
    2023-12-28 : Treviso - cintura urbana: Vegetale, Umido
    2023-12-30 : Treviso - cintura urbana: VPL
```

### CODE REVIEW

**Comment by CremaLuca** [comment]
I guess we could remove the less-reliable scraping-based Contarina source that was [merged last week](https://github.com/mampfes/hacs_waste_collection_schedule/pull/1542)

**Comment by 5ila5** [comment]
Thanks for your contribution

**Comment by alexdelli** [comment]
Hi, is it possible to separate the waste type on the same day?
Or we need to create a Source type called: Treviso - cintura urbana: Vegetale, Umido

thank you

**Comment by 5ila5** [comment]
@alexdelli you can use the regex and split_at parameter to clean the name and split them at a given separator I added description for this in #1715 you can now find it in the description (https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/contarina_it.md)

**Pull request merged**
