### PR TITLE
✨ ADD Canterbury City Council support

### PR DESCRIPTION
**Pull request by sultanhq**

### CODE REVIEW

**Comment by mampfes** [comment]
Please revert the formatting changes in README.md.

Is there a good reason for this changes? If yes, please create a separate PR.

**Comment by hdurdle** [comment]
> Please revert the formatting changes in README.md.
> 
> Is there a good reason for this changes? If yes, please create a separate PR.

I almost made the same mistake with my commit.  In my case Visual Studio Code's Markdown formatter was to blame.  Had to turn off format on save to stop it messing with the formatting.

**Comment by sultanhq** [comment]
Apologies @mampfes , my prettier appeared to have a different opinion to markdown to me 🙄

**Comment by mampfes** [comment]
Thanks for your contribution.

**Pull request merged**
