### PR TITLE
Add support for movar_no

### PR DESCRIPTION
**Pull request by seedzero**
Per request https://github.com/mampfes/hacs_waste_collection_schedule/issues/718

### CODE REVIEW

**Comment by mampfes** [comment]
Thanks for your contribution.

**Comment by agoberg2** [comment]
I wonder if this has stopped working when we entered 2024?

**Comment by seedzero** [comment]
> I wonder if this has stopped working when we entered 2024?

@agoberg2 Looking at the website, the  "KommuneLimit" values have changed from "3019,3002,3017,3018" to "3103,3112,3114,3216"
My understanding is that these are postal codes for Vestby, Moss, Våler and Råde. Have these codes changed? It works if I update the values to 3103, 3112, 3114, 3216.

**Comment by seedzero** [comment]
@agoberg2 I think these values have changed? https://snl.no/Råde

**Comment by seedzero** [comment]
https://github.com/mampfes/hacs_waste_collection_schedule/pull/1626

**Pull request merged**
