### PR TITLE
Introduce VS Code debug config

### PR DESCRIPTION
**Pull request by tathamoddie**
This allows you to be editing a source script in VS Code, then just press F5 to run it through the test script with the debugger attached.

### CODE REVIEW

**Comment by 5ila5** [comment]
I generally like this, but I would probably add the -t option as debugging should probably print the whole stacktrace for better debugging.

I'd also like a third option debugging ics (yaml) source and just change the `-s` to a `-y`

**Comment by tathamoddie** [comment]
> I generally like this, but I would probably add the -t option as debugging should probably print the whole stacktrace for better debugging.
> 
> I'd also like a third option debugging ics (yaml) source and just change the `-s` to a `-y`

Both updates made. 👍

**Comment by 5ila5** [comment]
Nothing changed, did you push the right thing?

**Comment by tathamoddie** [comment]
Oops, sorry.

Fixed.

**Comment by 5ila5** [comment]
Thanks for your contribution

**Pull request merged**
